<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\HR\SSAS.HR.API\SSAS.HR.API.csproj" />
    <ProjectReference Include="..\..\src\Modules\HR\SSAS.HR.Application\SSAS.HR.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\HR\SSAS.HR.Domain\SSAS.HR.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\HR\SSAS.HR.Infrastructure\SSAS.HR.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\HR\SSAS.HR.Contracts\SSAS.HR.Contracts.csproj" />
  </ItemGroup>

</Project>
