using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Globalization;
using SSAS.BuildingBlocks.Localization.Catalog;

namespace SSAS.Localization.CatalogTool;

internal static class GeneratedCatalogWriter
{
  private const string NewLine = "\r\n";
  private static readonly JsonSerializerOptions ClientJsonOptions = new()
  {
    Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    WriteIndented = true
  };
  private static readonly JsonSerializerOptions QuoteJsonOptions = new()
  {
    Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
  };

  public static (byte[] Backend, byte[] Client) Generate(CatalogValidationResult validation)
  {
    if (!validation.IsValid || validation.Document is null)
    {
      throw new InvalidOperationException("Only a valid catalog can be generated.");
    }

    return (Encoding.UTF8.GetBytes(GenerateBackend(validation)), Encoding.UTF8.GetBytes(GenerateClient(validation)));
  }

  private static string GenerateBackend(CatalogValidationResult validation)
  {
    var document = validation.Document!;
    var builder = new StringBuilder();
    builder.Append("// <auto-generated />").Append(NewLine)
      .Append("using SSAS.BuildingBlocks.Localization.Catalog;").Append(NewLine).Append(NewLine)
      .Append("namespace SSAS.BuildingBlocks.Localization.Generated;").Append(NewLine).Append(NewLine)
      .Append("public static class GeneratedLocalizationCatalog").Append(NewLine)
      .Append('{').Append(NewLine)
      .Append("  public static ILocalizationCatalog Instance { get; } = Create();").Append(NewLine).Append(NewLine)
      .Append("  private static LocalizationCatalog Create()").Append(NewLine)
      .Append("  {").Append(NewLine)
      .Append("    return new LocalizationCatalog(").Append(NewLine)
      .Append(Invariant($"      CatalogSchemaVersion.Create({document.CatalogSchemaVersion}).Value,")).Append(NewLine)
      .Append(Invariant($"      CatalogVersion.Create({document.CatalogVersion}L).Value,")).Append(NewLine)
      .Append("      new LocalizationResourceDefinition[]").Append(NewLine)
      .Append("      {").Append(NewLine);

    foreach (var resource in validation.Resources)
    {
      builder.Append("        new(").Append(NewLine)
        .Append(Invariant($"          ResourceKey.Create({Quote(resource.ResourceKey.Value)}).Value,")).Append(NewLine)
        .Append(Invariant($"          {Quote(resource.Module)},")).Append(NewLine)
        .Append(Invariant($"          {Quote(resource.Group)},")).Append(NewLine)
        .Append(Invariant($"          LocalizationResourceCategory.{resource.Category},")).Append(NewLine)
        .Append(Invariant($"          LocalizationTextFormat.{resource.TextFormat},")).Append(NewLine)
        .Append(Invariant($"          LocalizationSecurityClassification.{resource.SecurityClassification},")).Append(NewLine)
        .Append(Invariant($"          {(resource.TenantOverridable ? "true" : "false")},")).Append(NewLine)
        .Append(Invariant($"          LocalizationResourceLifecycle.{resource.Lifecycle},")).Append(NewLine)
        .Append(Invariant($"          ResourceVersion.Create({resource.ResourceVersion.Value}).Value,")).Append(NewLine)
        .Append(Invariant($"          {Quote(resource.EnglishDefault)},")).Append(NewLine)
        .Append(Invariant($"          {Quote(resource.ArabicDefault)},")).Append(NewLine)
        .Append("          PlaceholderSet.Create(new string[] { ")
        .Append(string.Join(", ", resource.Placeholders.Names.Select(Quote)))
        .Append(" }).Value,").Append(NewLine)
        .Append(Invariant($"          PlaceholderFingerprint.FromBytes(Convert.FromHexString({Quote(resource.PlaceholderFingerprint.Hex)})).Value,")).Append(NewLine)
        .Append(Invariant($"          CompatibilityFingerprint.FromBytes(Convert.FromHexString({Quote(resource.CompatibilityFingerprint.Hex)})).Value,")).Append(NewLine)
        .Append(Invariant($"          {(resource.Description is null ? "null" : Quote(resource.Description))}),")).Append(NewLine);
    }

    builder.Append("      },").Append(NewLine)
      .Append(Invariant($"      {Quote(document.NeutralFallbacks.English)},")).Append(NewLine)
      .Append(Invariant($"      {Quote(document.NeutralFallbacks.Arabic)});")).Append(NewLine)
      .Append("  }").Append(NewLine)
      .Append('}').Append(NewLine);
    return builder.ToString();
  }

  private static string GenerateClient(CatalogValidationResult validation)
  {
    var document = validation.Document!;
    var resources = validation.Resources.Select(resource => new
    {
      resourceKey = resource.ResourceKey.Value,
      module = resource.Module,
      group = resource.Group,
      category = resource.Category.ToString(),
      textFormat = resource.TextFormat.ToString(),
      securityClassification = resource.SecurityClassification.ToString(),
      tenantOverridable = resource.TenantOverridable,
      lifecycle = resource.Lifecycle.ToString(),
      resourceVersion = resource.ResourceVersion.Value,
      placeholders = resource.Placeholders.Names,
      placeholderFingerprint = resource.PlaceholderFingerprint.Hex,
      compatibilityFingerprint = resource.CompatibilityFingerprint.Hex,
      defaults = new { en = resource.EnglishDefault, ar = resource.ArabicDefault },
      description = resource.Description
    });
    var artifact = new
    {
      catalogSchemaVersion = document.CatalogSchemaVersion,
      catalogVersion = document.CatalogVersion,
      neutralFallbacks = new { en = document.NeutralFallbacks.English, ar = document.NeutralFallbacks.Arabic },
      resources
    };
    var json = JsonSerializer.Serialize(artifact, ClientJsonOptions);
    return json.Replace("\r\n", "\n", StringComparison.Ordinal)
      .Replace("\n", NewLine, StringComparison.Ordinal) + NewLine;
  }

  private static string Quote(string value) => JsonSerializer.Serialize(value, QuoteJsonOptions);

  private static string Invariant(FormattableString value) => value.ToString(CultureInfo.InvariantCulture);
}
