using System.Globalization;

namespace SSAS.Platform.Domain.TenantStorage;

// The RESERVED, SYSTEM-CONTROLLED verification namespace (ADR-022 §17).
//
// IN THE DOMAIN rather than in the SQL provider, because the sweep that eventually consumes this vocabulary
// is a `DROP DATABASE`, and what a destructive operation is permitted to touch is a durability decision
// rather than a provider detail.
//
// "Deterministic naming" alone is explicitly NOT sufficient (§17). This type produces the names and
// recognises them; recognising a name is a NECESSARY condition for cleanup and never a sufficient one — the
// full conjunction additionally requires a matching durable verification record, an age threshold, absence
// from the tenant-database registry, absence of any assignment, and that no verification is active against
// it. A database must never be dropped because a string matched.
public static class TenantDatabaseVerificationNaming
{
  // The reserved marker. Deliberately distinctive and deliberately not a substring of anything the tenant
  // provisioning path produces.
  public const string ReservedPrefix = "SSAS_Verify_";

  // SQL Server identifiers are sysname — 128 characters. Every name this type produces is far shorter, and
  // the bound is asserted rather than assumed.
  public const int MaximumLength = 128;

  // `SSAS_Verify_<physical database identity>_<verification operation identity>`.
  //
  // The verification run identity is in the name for two reasons. It makes the name unique BY CONSTRUCTION,
  // so two operations can never target the same database and the collision Phase C had to close by evidence
  // simply cannot arise. And it points a human at the exact record that explains the database, which is
  // what an operator finding a stray database at 3am actually needs.
  //
  // Both components are positive integers, so the result is identifier-safe without escaping: there is no
  // caller-supplied text anywhere in it.
  public static string ForRun(long tenantDatabaseId, long verificationRunId)
  {
    ArgumentOutOfRangeException.ThrowIfNegativeOrZero(tenantDatabaseId);
    ArgumentOutOfRangeException.ThrowIfNegativeOrZero(verificationRunId);

    var name = string.Create(
      CultureInfo.InvariantCulture,
      $"{ReservedPrefix}{tenantDatabaseId}_{verificationRunId}");

    // Unreachable for any representable pair of Int64 values — the longest possible result is well under
    // half the limit — but asserted rather than trusted, because the cost of being wrong is a truncated
    // name that no longer correlates to its record.
    return name.Length <= MaximumLength
      ? name
      : throw new InvalidOperationException("The generated verification database name exceeded the SQL Server identifier limit.");
  }

  // Does this name belong to the reserved verification namespace at all?
  //
  // ORDINAL, and case-sensitive on purpose. SQL Server catalog collation varies by deployment, and a
  // destructive predicate must not become more permissive because a server happens to be case-insensitive.
  // Names are generated by this type, so an exact match is always available.
  public static bool IsVerificationDatabaseName(string? databaseName) =>
    !string.IsNullOrWhiteSpace(databaseName) &&
    databaseName.Length <= MaximumLength &&
    databaseName.StartsWith(ReservedPrefix, StringComparison.Ordinal) &&
    HasWellFormedSuffix(databaseName);

  // Is this name the one THIS run generated? The correlation step that turns "looks like ours" into
  // "is ours" (ADR-022 §17, compliance rule 24).
  public static bool MatchesRun(string? databaseName, long tenantDatabaseId, long verificationRunId) =>
    IsVerificationDatabaseName(databaseName) &&
    string.Equals(databaseName, ForRun(tenantDatabaseId, verificationRunId), StringComparison.Ordinal);

  // The suffix must be exactly `<digits>_<digits>`. Without this, `SSAS_Verify_` followed by anything at all
  // would be accepted, and the reserved namespace would be a prefix match wearing a longer string.
  private static bool HasWellFormedSuffix(string databaseName)
  {
    var suffix = databaseName.AsSpan(ReservedPrefix.Length);
    var separator = suffix.IndexOf('_');
    if (separator <= 0 || separator == suffix.Length - 1)
    {
      return false;
    }

    return IsAllDigits(suffix[..separator]) && IsAllDigits(suffix[(separator + 1)..]);
  }

  private static bool IsAllDigits(ReadOnlySpan<char> value)
  {
    if (value.IsEmpty)
    {
      return false;
    }

    foreach (var character in value)
    {
      // ASCII digits only. `char.IsDigit` accepts Unicode decimal digits from other scripts, which would
      // let a visually similar name into a namespace that authorises deletion.
      if (character is < '0' or > '9')
      {
        return false;
      }
    }

    return true;
  }
}
