<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Platform\SSAS.Platform.API\SSAS.Platform.API.csproj" />
    <ProjectReference Include="..\..\Platform\SSAS.Platform.Infrastructure\SSAS.Platform.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\HR\SSAS.HR.API\SSAS.HR.API.csproj" />
    <ProjectReference Include="..\..\Modules\Finance\SSAS.GL.API\SSAS.GL.API.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
