using Microsoft.Data.SqlClient;

namespace SSAS.Integration.Tests;

// The gate that stops orphaned test catalogs accumulating.
//
// The obvious guard — assert that TestCatalogJanitor recorded nothing — does not work, and was measured not
// working: xUnit gives no ordering guarantee, so it runs before most fixtures dispose and reports green
// while leaks are still being printed. A gate that passes in the presence of the defect it names is worse
// than no gate, because a green run then looks like proof.
//
// So this asserts on something ordering cannot affect: catalogs that were ALREADY on the instance when this
// test process started. Those cannot belong to the current run, so every one of them is a leak from a
// previous run — which is exactly the accumulation that reached 73 orphans unnoticed. In-run leaks are
// covered by the "[CATALOG LEAK]" marker TestCatalogJanitor writes to standard error, and by this same test
// on the NEXT run.
//
// CONCURRENCY BLIND SPOT, stated because it constrains how this suite may be run. This cannot tell a
// previous run's orphan from a CONCURRENT sibling suite's live catalog — both are simply SSAS_ databases
// older than this process. Running Integration and API against one instance at the same time will therefore
// fail this guard, and may fail it while nothing is actually wrong.
//
// The correct response is to SERIALISE THE RUNS, never to weaken the guard. This is the same limitation that
// made a startup sweep unacceptable: a sweep could not distinguish those two cases either, and it would have
// DROPPED the sibling's live catalogs instead of merely reporting them.
public sealed class CatalogLeakGuardTests
{
  [Fact]
  public async Task No_test_catalog_survived_a_previous_run()
  {
    // LOCAL time, deliberately. sys.databases.create_date is recorded in the server's local time, and the
    // test host runs on that same machine; comparing it against a UTC instant silently filtered out every
    // orphan on a non-UTC box, which is exactly how this guard first reported green with three leaks
    // sitting on the instance.
    var started = System.Diagnostics.Process.GetCurrentProcess().StartTime;

    await using var connection = new SqlConnection(
      new SqlConnectionStringBuilder(
        IntegrationSqlEnvironment.BaseConnectionString)
      {
        InitialCatalog = "master",
      }.ConnectionString);
    await connection.OpenAsync();

    await using var command = connection.CreateCommand();
    // THE PREDICATE IS DELIBERATELY LOOSE. Do not "tighten" it — that has been tried twice and was wrong
    // both times, because the suite has at least three unrelated naming shapes:
    //
    //   SSAS_<name>_<12 hex>              most fixtures
    //   SSAS_ERP_BACKUPP_<32 hex>         Guid.NewGuid().ToString("N") — backup and permission fixtures
    //   SSAS_Verify_<digits>_<digits>     TenantDatabaseVerificationNaming, generated by PRODUCTION code
    //
    // Matching 12-hex alone misses the last two; matching 12-hex plus Verify still misses the 32-hex ones.
    // A fourth shape arrives with the next fixture, and a guard that must be edited whenever someone adds a
    // fixture will silently stop guarding — which is the exact defect this whole slice exists to remove.
    //
    // So correctness comes from CONVENTION, not from pattern: SSAS_ is a RESERVED PREFIX for test catalogs,
    // the way production already reserves SSAS_Verify_. A scratch database must not use it. See
    // tests/Integration.Tests/README.md.
    command.CommandText =
      "SELECT name, create_date FROM sys.databases " +
      "WHERE name LIKE 'SSAS[_]%' AND create_date < @started ORDER BY create_date";
    command.Parameters.Add("@started", System.Data.SqlDbType.DateTime2).Value = started;

    var orphans = new List<string>();
    await using (var reader = await command.ExecuteReaderAsync())
    {
      while (await reader.ReadAsync())
      {
        orphans.Add($"{reader.GetString(0)} (created {reader.GetDateTime(1):u})");
      }
    }

    Assert.True(
      orphans.Count == 0,
      $"{orphans.Count} test catalog(s) survived an earlier run and are still on the instance.\n" +
      "Check standard error for [CATALOG LEAK] lines — they name the SQL error that stopped the drop.\n" +
      "To reap them, follow the enumerate-confirm-drop procedure in tests/Integration.Tests/README.md.\n" +
      "If a sibling suite is running against this instance right now, that is the cause: serialise the " +
      $"runs.\n  {string.Join("\n  ", orphans)}");
  }
}
