using System.Diagnostics;
using System.Globalization;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Options;
using SSAS.BuildingBlocks.Application.Abstractions.Identity;
using SSAS.BuildingBlocks.Domain;
using SSAS.HR.Domain.Employees;
using SSAS.BuildingBlocks.Application.Abstractions.Tenancy;
using SSAS.BuildingBlocks.Application.Abstractions.Time;
using SSAS.Platform.Application.Abstractions.Persistence;
using SSAS.Platform.Application.TenantStorage;
using SSAS.Platform.Domain.Branches;
using SSAS.Platform.Domain.Companies;
using SSAS.Platform.Domain.Enums;
using SSAS.Platform.Domain.TenantStorage;
using SSAS.Platform.Domain.Tenants;
using SSAS.Platform.Domain.ValueObjects;
using SSAS.Platform.Infrastructure.Persistence;
using SSAS.Platform.Infrastructure.Persistence.TenantErp;
using SSAS.Platform.Infrastructure.TenantStorage;
using Xunit.Abstractions;

namespace SSAS.Integration.Tests;

// THE SHARED → DEDICATED COPY, AGAINST REAL SQL (ADR-020, TS-Storage Phase E3).
//
// The claim is not "rows appeared in the target". It is:
//
//   exactly the requested tenant's rows, byte-for-byte identical on every copied column, with keys, audit
//   provenance and tenancy preserved, a target-generated rowversion, no co-tenant's data, and no partial
//   state that a retry could mistake for completion.
//
// Every assertion below reads the physical catalogs directly rather than trusting the engine's own report.
[Collection(TenantBackupSerialSuites.Name)]
public sealed class TenantCutoverCopySqlServerTests(ITestOutputHelper output)
{
  // ---- A. The load-bearing test: one tenant moves, the other is untouched on both sides.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task Copying_one_tenant_moves_only_that_tenant_and_leaves_its_co_tenant_alone()
  {
    await using var fixture = await CopyFixture.CreateAsync();
    await fixture.SeedCompaniesAsync(fixture.TenantA, 3, "AAA");
    await fixture.SeedCompaniesAsync(fixture.TenantB, 2, "BBB");
    var operationId = await fixture.BeginAndFreezeAsync();

    var copied = await fixture.CopyService().CopyAsync(operationId);

    Assert.True(copied.IsSuccess);
    Assert.Equal(3, copied.Value.TotalRows);

    // SEVEN TENANT-OWNED TABLES as of FP-007 Phase 1. Branch joined Company in Branch foundation B0;
    // Employee and EmployeeBranchAssignment joined them once the copy plan was derived from the
    // CONTRIBUTOR-COMPOSED model rather than a contributor-free one; Department, DepartmentManager and
    // EmployeeDepartmentAssignment joined in turn. Only Company holds rows in this fixture, so TotalRows is
    // unchanged while the table count is not — and this count is precisely what would have stayed at two
    // while a promotion silently left every employee behind.
    Assert.Equal(7, copied.Value.TablesCopied);
    Assert.Equal(0, copied.Value.TablesAlreadyComplete);
    Assert.Equal(
      [
        nameof(Branch),
        nameof(Company),
        "Department",
        "DepartmentManager",
        "Employee",
        "EmployeeBranchAssignment",
        "EmployeeDepartmentAssignment"
      ],
      copied.Value.Tables.Select(table => table.EntityName).OrderBy(name => name, StringComparer.Ordinal));

    // TENANT A IS ON THE TARGET, AND ONLY TENANT A.
    Assert.Equal(3, await fixture.TargetCompanyCountAsync(fixture.TenantA));
    Assert.Equal(0, await fixture.TargetCompanyCountAsync(fixture.TenantB));
    Assert.Equal(3, await fixture.TargetCompanyCountAsync(null));

    // THE SHARED SOURCE IS UNCHANGED. A copy is not a move: nothing is deleted from the source, and the
    // co-tenant sharing the physical database is untouched.
    Assert.Equal(3, await fixture.SourceCompanyCountAsync(fixture.TenantA));
    Assert.Equal(2, await fixture.SourceCompanyCountAsync(fixture.TenantB));
  }

  // ---- C + D. Audit provenance verbatim; rowversion regenerated by the target.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task Audit_values_are_copied_verbatim_and_rowversion_is_target_generated()
  {
    await using var fixture = await CopyFixture.CreateAsync();
    await fixture.SeedCompaniesAsync(fixture.TenantA, 4, "AUD");
    var operationId = await fixture.BeginAndFreezeAsync();

    // ROWVERSION IS A PER-DATABASE COUNTER, so "source bytes != target bytes" is NOT a proof — two freshly
    // created databases can legitimately issue identical values, and an earlier version of this test failed
    // for exactly that reason rather than because anything was wrong.
    //
    // The deterministic proof is to push the TARGET's counter far past anything the source could hold, then
    // require every copied row's rowversion to sit above that watermark. A rowversion carried over from the
    // source would necessarily fall below it.
    await fixture.AdvanceTargetRowVersionCounterAsync();
    var watermark = await fixture.TargetRowVersionWatermarkAsync();

    var sourceRows = await CopyFixture.ReadCompaniesAsync(fixture.SourceCatalog, fixture.TenantA);
    Assert.All(sourceRows.Values, row => Assert.True(
      Counter(row.RowVersion) < watermark,
      "the source counter is not below the target watermark, so this test would prove nothing"));

    Assert.True((await fixture.CopyService().CopyAsync(operationId)).IsSuccess);
    var targetRows = await CopyFixture.ReadCompaniesAsync(fixture.TargetCatalog, fixture.TenantA);

    Assert.Equal(sourceRows.Count, targetRows.Count);
    foreach (var (key, source) in sourceRows)
    {
      var target = targetRows[key];

      // VERBATIM. Not "recent", not "re-stamped by the copy" — the same provenance the source recorded.
      Assert.Equal(source.CreatedUtc, target.CreatedUtc);
      Assert.Equal(source.CreatedBy, target.CreatedBy);
      Assert.Equal(source.ModifiedUtc, target.ModifiedUtc);
      Assert.Equal(source.ModifiedBy, target.ModifiedBy);
      Assert.Equal(source.StatusChangedUtc, target.StatusChangedUtc);
      Assert.Equal(source.StatusChangedBy, target.StatusChangedBy);
      Assert.Equal(source.TenantId, target.TenantId);
      Assert.Equal(source.CompanyCode, target.CompanyCode);

      // ROWVERSION IS THE TARGET'S OWN, issued by the target's counter during this copy.
      Assert.NotNull(target.RowVersion);
      Assert.NotEmpty(target.RowVersion!);
      Assert.True(
        Counter(target.RowVersion) > watermark,
        "the target rowversion predates the copy, so it was not generated by the target");
    }
  }

  // rowversion is an 8-byte big-endian database counter.
  private static ulong Counter(byte[] rowVersion) =>
    System.Buffers.Binary.BinaryPrimitives.ReadUInt64BigEndian(rowVersion);

  // ---- H. Retry after a completed table: re-validated, skipped, not duplicated.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task A_retry_revalidates_completed_tables_and_never_duplicates_them()
  {
    await using var fixture = await CopyFixture.CreateAsync();
    await fixture.SeedCompaniesAsync(fixture.TenantA, 5, "RTY");
    var operationId = await fixture.BeginAndFreezeAsync();

    var first = await fixture.CopyService().CopyAsync(operationId);
    Assert.True(first.IsSuccess);
    // The whole tenant-owned manifest: Branch and Company, plus the two HR tables the contributor-composed
    // model added in FP-006C6 and the three FP-007 Phase 1 added.
    Assert.Equal(7, first.Value.TablesCopied);

    // The retry a dead process's replacement would perform.
    var second = await fixture.CopyService().CopyAsync(operationId);

    Assert.True(second.IsSuccess);

    // COMPANY IS RECOGNISED AS ALREADY COMPLETE. The six empty tables are not, and that is correct rather
    // than a gap: an empty table is indistinguishable from one that was never copied, so the engine copies
    // each again, moving nothing. The retry's safety claim is about not DUPLICATING rows, which the counts
    // below still prove exactly.
    Assert.Equal(6, second.Value.TablesCopied);
    Assert.Equal(1, second.Value.TablesAlreadyComplete);
    Assert.Equal(5, second.Value.TotalRows);

    // Skipping is proven by the row count, not only by the report: a second insert would have doubled it.
    Assert.Equal(5, await fixture.TargetCompanyCountAsync(fixture.TenantA));
  }

  // ---- G + O. A target holding a PARTIAL copy is inconsistent, and is refused rather than topped up.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task A_partially_populated_target_is_refused_rather_than_completed()
  {
    await using var fixture = await CopyFixture.CreateAsync();
    await fixture.SeedCompaniesAsync(fixture.TenantA, 4, "PRT");
    var operationId = await fixture.BeginAndFreezeAsync();

    Assert.True((await fixture.CopyService().CopyAsync(operationId)).IsSuccess);

    // Something removed a row from the target — the shape a torn write or an operator would leave.
    await fixture.DeleteOneTargetCompanyAsync(fixture.TenantA);
    Assert.Equal(3, await fixture.TargetCompanyCountAsync(fixture.TenantA));

    var retried = await fixture.CopyService().CopyAsync(operationId);

    Assert.True(retried.IsFailure);
    Assert.Equal(TenantStorageErrors.CutoverTargetInconsistent.Code, retried.Error.Code);

    // NOTHING WAS REPAIRED AND NOTHING WAS DELETED. The divergence is evidence, and the engine preserves it.
    Assert.Equal(3, await fixture.TargetCompanyCountAsync(fixture.TenantA));
  }

  // ---- O (extra row). Same keys plus one the source does not have. Needs no trigger surgery, so this is
  // the half of "extra/missing" that a purely additive corruption would produce.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task An_extra_target_row_is_detected_and_refused()
  {
    await using var fixture = await CopyFixture.CreateAsync();
    await fixture.SeedCompaniesAsync(fixture.TenantA, 3, "XTR");
    var operationId = await fixture.BeginAndFreezeAsync();

    Assert.True((await fixture.CopyService().CopyAsync(operationId)).IsSuccess);
    await fixture.AddExtraTargetCompanyAsync(fixture.TenantA);
    Assert.Equal(4, await fixture.TargetCompanyCountAsync(fixture.TenantA));

    var retried = await fixture.CopyService().CopyAsync(operationId);

    Assert.True(retried.IsFailure);
    Assert.Equal(TenantStorageErrors.CutoverTargetInconsistent.Code, retried.Error.Code);
    Assert.Equal(4, await fixture.TargetCompanyCountAsync(fixture.TenantA));
  }

  // ---- §15 TRIGGER REVIEW, read from the server rather than assumed.
  //
  // The tenant schema carries exactly one DML trigger, it is INSTEAD OF DELETE, and it is therefore not on
  // the copy's path — the copy only inserts. It is left ENABLED on the target throughout, so the target
  // inherits the same retention invariant the source has.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task The_only_tenant_trigger_is_a_delete_guard_that_the_copy_neither_fires_nor_disturbs()
  {
    await using var fixture = await CopyFixture.CreateAsync();
    await fixture.SeedCompaniesAsync(fixture.TenantA, 3, "TRG");
    var operationId = await fixture.BeginAndFreezeAsync();

    var before = await CopyFixture.TriggersAsync(fixture.TargetCatalog);
    var trigger = Assert.Single(before);
    Assert.Equal("TR_Companies_PreventDelete", trigger.Name);
    Assert.Contains("INSTEAD OF", trigger.Type, StringComparison.Ordinal);
    Assert.Contains("DELETE", trigger.Type, StringComparison.Ordinal);
    Assert.DoesNotContain("INSERT", trigger.Type, StringComparison.Ordinal);
    Assert.False(trigger.Disabled);

    Assert.True((await fixture.CopyService().CopyAsync(operationId)).IsSuccess);

    // Still exactly one trigger, still enabled: the copy did not disable it to make itself possible.
    var after = Assert.Single(await CopyFixture.TriggersAsync(fixture.TargetCatalog));
    Assert.Equal("TR_Companies_PreventDelete", after.Name);
    Assert.False(after.Disabled);

    // ...and it is live on the target, so the copied database refuses physical deletion exactly as the
    // source does. This is also what makes the engine's "never delete to make progress" rule unbreakable.
    var refused = await Assert.ThrowsAsync<SqlException>(() =>
      fixture.AttemptTargetDeleteAsync(fixture.TenantA));
    Assert.Contains("cannot be physically deleted", refused.Message, StringComparison.Ordinal);
  }

  // ---- N. Exact validation catches a changed business value, which no row count would see.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task Exact_validation_detects_a_changed_target_business_value()
  {
    await using var fixture = await CopyFixture.CreateAsync();
    await fixture.SeedCompaniesAsync(fixture.TenantA, 3, "CHG");
    var operationId = await fixture.BeginAndFreezeAsync();

    Assert.True((await fixture.CopyService().CopyAsync(operationId)).IsSuccess);

    // Same row count, same keys, one different value.
    await fixture.MutateOneTargetCompanyNameAsync(fixture.TenantA);
    Assert.Equal(3, await fixture.TargetCompanyCountAsync(fixture.TenantA));

    var retried = await fixture.CopyService().CopyAsync(operationId);

    Assert.True(retried.IsFailure);
    Assert.Equal(TenantStorageErrors.CutoverTargetInconsistent.Code, retried.Error.Code);
  }

  // ---- F. A dedicated target holding another tenant's rows is not a dedicated target.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task A_target_containing_another_tenants_rows_refuses_the_copy_and_writes_nothing()
  {
    await using var fixture = await CopyFixture.CreateAsync();
    await fixture.SeedCompaniesAsync(fixture.TenantA, 3, "CON");
    await fixture.SeedTargetCompaniesAsync(fixture.TenantB, 1, "FOREIGN");
    var operationId = await fixture.BeginAndFreezeAsync();

    var copied = await fixture.CopyService().CopyAsync(operationId);

    Assert.True(copied.IsFailure);
    Assert.Equal(TenantStorageErrors.CutoverTargetContaminated.Code, copied.Error.Code);

    // REFUSED BEFORE ANY WRITE. Contamination is checked across every table before the first insert, so the
    // engine never half-populates a database it has decided not to trust.
    Assert.Equal(0, await fixture.TargetCompanyCountAsync(fixture.TenantA));
    Assert.Equal(1, await fixture.TargetCompanyCountAsync(fixture.TenantB));
  }

  // ---- K. Copy runs only inside an established freeze.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task A_cutover_that_is_not_frozen_cannot_be_copied()
  {
    await using var fixture = await CopyFixture.CreateAsync();
    await fixture.SeedCompaniesAsync(fixture.TenantA, 2, "NFZ");

    // Preparing: the source is still writable, so copying from it would read a moving database.
    var operationId = await fixture.BeginAsync();
    var preparing = await fixture.CopyService().CopyAsync(operationId);
    Assert.True(preparing.IsFailure);
    Assert.Equal(TenantStorageErrors.CutoverOperationNotFrozen.Code, preparing.Error.Code);
    Assert.Equal(0, await fixture.TargetCompanyCountAsync(fixture.TenantA));

    // Abandoned: released pre-flip, so there is no freeze to copy under.
    Assert.True((await fixture.FreezeService().FreezeAsync(operationId)).IsSuccess);
    Assert.True((await fixture.FreezeService().ReleaseFreezeAsync(operationId, "test")).IsSuccess);
    var abandoned = await fixture.CopyService().CopyAsync(operationId);
    Assert.True(abandoned.IsFailure);
    Assert.Equal(TenantStorageErrors.CutoverOperationNotFrozen.Code, abandoned.Error.Code);
  }

  // ---- L. Endpoint drift: the tenant no longer routes to the operation's recorded source.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task A_source_the_tenant_no_longer_routes_to_refuses_the_copy()
  {
    await using var fixture = await CopyFixture.CreateAsync();
    await fixture.SeedCompaniesAsync(fixture.TenantA, 2, "DRF");
    var operationId = await fixture.BeginAndFreezeAsync();

    // Routing moved underneath the operation. Copying from the recorded source would copy stale data.
    await fixture.RepointAssignmentAsync(fixture.TenantA, fixture.SecondSharedDatabaseId);

    var copied = await fixture.CopyService().CopyAsync(operationId);

    Assert.True(copied.IsFailure);
    Assert.Equal(TenantStorageErrors.CutoverSourceNotEligible.Code, copied.Error.Code);
    Assert.Equal(0, await fixture.TargetCompanyCountAsync(fixture.TenantA));
  }

  // ---- M. Both schemas must be current. No implicit migration as a side effect of copying.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task An_unmigrated_target_refuses_the_copy_rather_than_migrating_itself()
  {
    await using var fixture = await CopyFixture.CreateAsync(migrateTarget: false);
    await fixture.SeedCompaniesAsync(fixture.TenantA, 2, "SCH");
    var operationId = await fixture.BeginAndFreezeAsync();

    var copied = await fixture.CopyService().CopyAsync(operationId);

    Assert.True(copied.IsFailure);
    Assert.Equal(TenantStorageErrors.CutoverSchemaIncompatible.Code, copied.Error.Code);

    // The target is still unmigrated: the copy did not quietly apply DDL to make itself possible.
    Assert.False(await fixture.TargetHasCompaniesTableAsync());
  }

  // ---- I. Two executors, one cutover. The database decides which one owns it.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task Only_one_instance_can_execute_a_cutover_copy_at_a_time()
  {
    await using var fixture = await CopyFixture.CreateAsync();
    await fixture.SeedCompaniesAsync(fixture.TenantA, 6, "OWN");
    var operationId = await fixture.BeginAndFreezeAsync();

    // Instance one, holding ownership exactly as a running copy does.
    await using var owner = new SqlConnection(fixture.PlatformConnectionString);
    await owner.OpenAsync();
    Assert.True(await TenantCutoverOperationLock.TryAcquireForSessionAsync(
      owner, operationId, TimeSpan.FromSeconds(5)));

    var contender = await fixture.CopyService().CopyAsync(operationId);

    Assert.True(contender.IsFailure);
    Assert.Equal(TenantStorageErrors.CutoverCopyOwnershipNotAcquired.Code, contender.Error.Code);
    Assert.Equal(0, await fixture.TargetCompanyCountAsync(fixture.TenantA));

    // OWNERSHIP IS TRANSIENT: dropping the connection — as a dying process would — releases it, and a retry
    // simply proceeds. No lease expiry, no stale-owner cleanup.
    await owner.CloseAsync();
    var resumed = await fixture.CopyService().CopyAsync(operationId);
    Assert.True(resumed.IsSuccess);
    Assert.Equal(6, await fixture.TargetCompanyCountAsync(fixture.TenantA));
  }

  // Two genuinely concurrent executors: whatever the interleaving, the target is exact and undoubled.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task Two_concurrent_copies_cannot_corrupt_or_duplicate_the_target()
  {
    await using var fixture = await CopyFixture.CreateAsync();
    await fixture.SeedCompaniesAsync(fixture.TenantA, 8, "RACE");
    var operationId = await fixture.BeginAndFreezeAsync();

    var attempts = await Task.WhenAll(
      Task.Run(() => fixture.CopyService().CopyAsync(operationId)),
      Task.Run(() => fixture.CopyService().CopyAsync(operationId)));

    // At least one succeeds; any loser lost on ownership rather than on corruption.
    Assert.Contains(attempts, attempt => attempt.IsSuccess);
    foreach (var failed in attempts.Where(attempt => attempt.IsFailure))
    {
      Assert.Equal(TenantStorageErrors.CutoverCopyOwnershipNotAcquired.Code, failed.Error.Code);
    }

    Assert.Equal(8, await fixture.TargetCompanyCountAsync(fixture.TenantA));
    Assert.Equal(8, await fixture.TargetCompanyCountAsync(null));
  }

  // ---- J. THE RACE E1 COULD NOT SEE. A release must not be able to unfreeze the source under a copy.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task A_freeze_cannot_be_released_while_a_copy_owns_the_operation()
  {
    await using var fixture = await CopyFixture.CreateAsync();
    await fixture.SeedCompaniesAsync(fixture.TenantA, 3, "REL");
    var operationId = await fixture.BeginAndFreezeAsync();

    // A copy is executing: it owns the operation.
    await using var copyOwner = new SqlConnection(fixture.PlatformConnectionString);
    await copyOwner.OpenAsync();
    Assert.True(await TenantCutoverOperationLock.TryAcquireForSessionAsync(
      copyOwner, operationId, TimeSpan.FromSeconds(5)));

    var released = await fixture.FreezeService().ReleaseFreezeAsync(operationId, "operator changed mind");

    // REFUSED, NOT DELAYED. Unfreezing here would let source writes resume while the copy is still reading.
    Assert.True(released.IsFailure);
    Assert.Equal(TenantStorageErrors.CutoverReleaseBlockedByActiveCopy.Code, released.Error.Code);

    // The durable state is untouched, so the source is still frozen...
    Assert.Equal(TenantCutoverOperationStatus.Frozen, (await fixture.ReadAsync(operationId)).Status);

    // ---- P. ...and a tenant write is still refused while the copy holds the operation.
    await using (var writer = fixture.SourceTenantContext(fixture.TenantA))
    {
      writer.Companies.Add(CopyFixture.NewCompany(fixture.TenantA, "DURING"));
      var refused = await Assert.ThrowsAsync<TenantStorageUnavailableException>(
        () => writer.SaveChangesAsync());
      Assert.Equal(TenantStorageErrors.TenantWritesFrozen.Code, refused.Error.Code);
    }

    // ---- Q. The co-tenant on the same shared database is unaffected throughout.
    await using (var coTenant = fixture.SourceTenantContext(fixture.TenantB))
    {
      coTenant.Companies.Add(CopyFixture.NewCompany(fixture.TenantB, "OTHER"));
      Assert.Equal(1, await coTenant.SaveChangesAsync());
    }

    // Once the copy's connection is gone, release works normally — a tenant is never permanently frozen.
    await copyOwner.CloseAsync();
    Assert.True((await fixture.FreezeService().ReleaseFreezeAsync(operationId, "done")).IsSuccess);
  }

  // ---- B + E. Identity preservation and foreign-key ordering, proven on real tables.
  //
  // No tenant entity uses an identity key or a foreign key TODAY, so these mechanisms would otherwise be
  // asserted only in the abstract. The probe model exercises the SAME plan derivation and the SAME copier
  // the engine uses, against real tables with a real FK and a real IDENTITY column.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task Identity_keys_and_foreign_key_order_survive_a_real_copy()
  {
    await using var fixture = await CopyFixture.CreateAsync();
    await CopyFixture.CreateProbeTablesAsync(fixture.SourceCatalog);
    await CopyFixture.CreateProbeTablesAsync(fixture.TargetCatalog);
    await fixture.SeedProbeDataAsync(fixture.TenantA);
    await fixture.SeedProbeDataAsync(fixture.TenantB);

    await using var probe = new ProbeContext();
    var plan = TenantCutoverCopyPlan.Build(probe.Model);
    Assert.True(plan.IsSuccess);

    // PRINCIPALS BEFORE DEPENDENTS. Derived from the model's foreign keys, not from table names — the
    // dependent sorts alphabetically first, so an alphabetical order would insert it before its parent.
    Assert.Equal(
      [nameof(ProbeParent), nameof(ProbeChild)],
      plan.Value.Select(table => table.EntityName).ToArray());
    Assert.True(Assert.Single(plan.Value, table => table.EntityName == nameof(ProbeParent)).HasIdentityColumn);

    var options = new TenantCutoverCopyOptions();
    var copier = new TenantCutoverTableCopier(options);
    var validator = new TenantCutoverCopyValidator(options);

    await using var source = new SqlConnection(CopyFixture.ConnectionFor(fixture.SourceCatalog));
    await using var target = new SqlConnection(CopyFixture.ConnectionFor(fixture.TargetCatalog));
    await source.OpenAsync();
    await target.OpenAsync();

    foreach (var table in plan.Value)
    {
      await using var transaction = (SqlTransaction)await target.BeginTransactionAsync();
      await copier.CopyAsync(table, fixture.TenantA, source, target, transaction);
      var validation = await validator.ValidateAsync(table, fixture.TenantA, source, target, transaction);
      Assert.True(validation.IsExact, validation.Difference);
      await transaction.CommitAsync();
    }

    // IDENTITY VALUES ARE THE SAME ON BOTH SIDES, which is what makes the child's foreign key still point at
    // the row it pointed at before the move.
    var sourceParents = await CopyFixture.ProbeParentIdsAsync(fixture.SourceCatalog, fixture.TenantA);
    var targetParents = await CopyFixture.ProbeParentIdsAsync(fixture.TargetCatalog, fixture.TenantA);
    Assert.Equal(sourceParents, targetParents);
    Assert.NotEmpty(targetParents);

    // The children arrived, their FK survived enforcement (CheckConstraints is on), and the co-tenant's
    // rows did not travel.
    Assert.Equal(4, await CopyFixture.ProbeChildCountAsync(fixture.TargetCatalog, fixture.TenantA));
    Assert.Equal(0, await CopyFixture.ProbeChildCountAsync(fixture.TargetCatalog, fixture.TenantB));
    Assert.Equal(0, await CopyFixture.OrphanedProbeChildCountAsync(fixture.TargetCatalog));
  }

  // ---- آ§18 performance, and آ§14 / LOW-3 plan measurement, at meaningful volume.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task A_large_tenant_copies_by_streaming_and_every_query_seeks()
  {
    await using var fixture = await CopyFixture.CreateAsync();
    const int rows = 20_000;
    await fixture.SeedCompaniesAsync(fixture.TenantA, rows, "PERF");
    await fixture.SeedCompaniesAsync(fixture.TenantB, 5_000, "NOISE");
    var operationId = await fixture.BeginAndFreezeAsync();

    // Cutover history, so the E1 write-fence lookup is measured against an accumulated table rather than a
    // one-row fixture (LOW-3).
    await fixture.SeedCutoverHistoryAsync(5_000);
    await fixture.RefreshStatisticsAsync();

    var before = GC.GetTotalAllocatedBytes();
    var stopwatch = Stopwatch.StartNew();
    var copied = await fixture.CopyService().CopyAsync(operationId);
    stopwatch.Stop();
    var allocated = GC.GetTotalAllocatedBytes() - before;

    Assert.True(copied.IsSuccess);
    Assert.Equal(rows, copied.Value.TotalRows);
    Assert.Equal(rows, await fixture.TargetCompanyCountAsync(fixture.TenantA));
    Assert.Equal(0, await fixture.TargetCompanyCountAsync(fixture.TenantB));

    var perSecond = rows / Math.Max(stopwatch.Elapsed.TotalSeconds, 0.001);
    output.WriteLine(
      $"Copied+validated {rows} rows (co-tenant noise 5000) in {stopwatch.ElapsedMilliseconds}ms " +
      $"= {perSecond:F0} rows/sec, batch size {new TenantCutoverCopyOptions().BatchSize}, " +
      $"allocated {allocated / 1024 / 1024}MB ({(double)allocated / rows:F0} bytes/row).");

    // STREAMING, NOT MATERIALISED. Copy and validation each walk both sides once; a design that loaded the
    // tenant into memory would allocate on the order of the row payload times the row count.
    Assert.True(
      allocated < 256L * 1024 * 1024,
      $"copy allocated {allocated / 1024 / 1024}MB for {rows} rows, which is not streaming behaviour");

    // Issue both shapes through the real components, which records the exact statements production sends.
    // The plans are then taken from the server by replaying those statements, so nothing here depends on
    // what the plan cache still happens to remember.
    await fixture.ReissueMeasuredQueriesAsync();

    var plans = await fixture.CapturePlansAsync();
    Assert.True(
      plans.Count == 2,
      $"expected both reviewed query plans, captured: {string.Join(", ", plans.Select(plan => plan.Label))}");

    // The source read, and the E1 write-fence lookup (LOW-3), from the server's own plans.
    foreach (var measured in plans)
    {
      output.WriteLine(
        $"{measured.Label}: {measured.Operation} on {measured.Index}, " +
        $"{measured.LogicalReadsPerExecution} logical reads/execution, " +
        $"{measured.MicrosecondsPerExecution}us/execution over {measured.ExecutionCount} executions.");

      // No heap scan anywhere: every table under review is clustered and reached through it.
      Assert.DoesNotContain("PhysicalOp=\"Table Scan\"", measured.PlanXml, StringComparison.Ordinal);

      // AND NO SORT. The copy reads ORDER BY primary key and the validation walks both sides in that order;
      // if either needed an explicit Sort, a large tenant would spill to tempdb and the "streaming" claim
      // would be false. The clustered index already provides the order.
      Assert.False(measured.HasSort, $"{measured.Label} required an explicit Sort: {measured.Operation}");
    }
  }

  private sealed record MeasuredPlan(
    string Label,
    string PlanXml,
    long LogicalReadsPerExecution,
    long MicrosecondsPerExecution,
    long ExecutionCount)
  {
    // ALL operators and ALL indexes, not the first of each: the first PhysicalOp in a plan is often an outer
    // Compute Scalar or Top, and reporting that as "the operation" would describe the wrapper rather than
    // the access path under review.
    public string Operation => string.Join(" -> ", Values("PhysicalOp=\""));

    public string Index => Values("Index=\"") is { Count: > 0 } indexes
      ? string.Join(", ", indexes.Distinct(StringComparer.Ordinal))
      : "(none)";

    public bool HasSort => Values("PhysicalOp=\"").Contains("Sort", StringComparer.Ordinal);

    private List<string> Values(string marker)
    {
      var values = new List<string>();
      var cursor = 0;
      while (true)
      {
        var start = PlanXml.IndexOf(marker, cursor, StringComparison.Ordinal);
        if (start < 0)
        {
          return values;
        }

        start += marker.Length;
        var end = PlanXml.IndexOf('"', start);
        if (end < 0)
        {
          return values;
        }

        values.Add(PlanXml[start..end]);
        cursor = end;
      }
    }
  }

  // ================================================================================================
  // C6 — SHARED → DEDICATED CARRIES THE MODULE-CONTRIBUTED ENTITIES (FP-006C6, ADR-020, ADR-017).
  // ================================================================================================
  //
  // ---- WHAT WAS ACTUALLY BROKEN, AND WHY NOTHING CAUGHT IT.
  //
  // The copy manifest is derived from the tenant model, which is the right design — a hand-written table
  // list is wrong the moment someone adds an entity, and wrong silently. But the model it derived from was
  // built with NO contributors, so it could not contain Employee no matter what HR registered.
  //
  // A promotion therefore copied Companies and Branches, validated every row it copied, reported success,
  // and left every employee and every branch-assignment record behind. There was no error to notice: the
  // copy was faithful to the model it was given, and the model was the wrong one.
  //
  // These proofs run the REAL copy service against real SQL Server with the contributor set the Host
  // registers.

  // ---- C6-1 / C6-2. THE MODEL THE CUTOVER PLANS FROM IS THE ONE THE APPLICATION PERSISTS THROUGH.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public void C6_1_C6_2_The_cutover_manifest_covers_every_contributed_tenant_owned_entity()
  {
    var composed = CutoverTenantModel.Source.Model;

    // The runtime model contains all seven — two from Platform, two from FP-006, three from FP-007 Phase 1...
    var derived = composed.GetEntityTypes()
      .Where(entity => !entity.IsOwned())
      .Where(entity => typeof(ITenantOwnedEntity).IsAssignableFrom(entity.ClrType))
      .Where(entity => entity.GetTableName() is not null)
      .Select(entity => entity.ClrType.Name)
      .OrderBy(name => name, StringComparer.Ordinal)
      .ToArray();

    // AN EXACT LIST, DELIBERATELY. The derivation guarantees the engine cannot MISS a table; this
    // guarantees a human SEES a new one, because a new tenant-owned entity may need ordering, identity or
    // column decisions that "it compiles" does not settle. FP-007 Phase 1 added three, and this is one of
    // the three places that said so.
    Assert.Equal(
      [
        "Branch",
        "Company",
        "Department",
        "DepartmentManager",
        "Employee",
        "EmployeeBranchAssignment",
        "EmployeeDepartmentAssignment"
      ],
      derived);

    // ...and the plan derived for the copy covers exactly that set, with nothing declared by hand.
    var plan = TenantCutoverCopyPlan.Build(composed);
    Assert.True(plan.IsSuccess);
    Assert.Equal(
      derived,
      plan.Value.Select(table => table.EntityName).OrderBy(name => name, StringComparer.Ordinal));
  }

  // ================================================================================================
  // C6-15. THE COPY ORDER PUTS DEPARTMENTS BEFORE EMPLOYEES (FP-007 Phase 3).
  // ================================================================================================
  //
  // Employee gained a REQUIRED foreign key to Department, so a copy that inserted employees first would
  // fail on that constraint against a target where the departments did not exist yet. The plan is a
  // topological sort over the model's foreign keys, so the ordering is derived rather than declared — and
  // derived means nobody wrote it down, which is exactly why it is worth asserting.
  //
  // ---- AND WHY THIS IS NOT MERELY THE SQL TESTS RESTATED.
  //
  // The real-SQL copies below would fail if the order were wrong, but only for the tables the fixture
  // happens to populate, and only after twenty minutes. This reads the order directly out of the plan, in
  // milliseconds, for every pair that matters — including DepartmentManagers and
  // EmployeeDepartmentAssignments, which point at BOTH principals.
  //
  // It is also the guard for the ADR-026 decision 7 split. If DepartmentManager were ever folded back onto
  // Department as a ManagerEmployeeId column, Department would depend on Employee while Employee depends on
  // Department, the sort would find a cycle, and Build would fail with CutoverCopyOrderUndecidable rather
  // than producing a wrong order.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public void C6_15_The_copy_order_places_every_principal_before_its_dependents()
  {
    var plan = TenantCutoverCopyPlan.Build(CutoverTenantModel.Source.Model);

    Assert.True(plan.IsSuccess, plan.IsFailure ? plan.Error.Code : null);

    var order = plan.Value.Select(table => table.EntityName).ToArray();

    int PositionOf(string entity)
    {
      var index = Array.IndexOf(order, entity);

      Assert.True(index >= 0, $"{entity} is absent from the copy manifest entirely.");

      return index;
    }

    // Company and Branch are Platform's, and everything HR-owned depends on one or both.
    Assert.True(PositionOf(nameof(Company)) < PositionOf("Department"));
    Assert.True(PositionOf(nameof(Company)) < PositionOf(nameof(Employee)));
    Assert.True(PositionOf(nameof(Branch)) < PositionOf(nameof(Employee)));

    // ---- THE FP-007 PHASE 3 EDGE. This is the one the new foreign key created.
    Assert.True(
      PositionOf("Department") < PositionOf(nameof(Employee)),
      "Departments must be copied before Employees: Employee.DepartmentId is a required foreign key.");

    // The two tables that depend on BOTH must come after both.
    Assert.True(PositionOf("Department") < PositionOf("DepartmentManager"));
    Assert.True(PositionOf(nameof(Employee)) < PositionOf("DepartmentManager"));
    Assert.True(PositionOf("Department") < PositionOf("EmployeeDepartmentAssignment"));
    Assert.True(PositionOf(nameof(Employee)) < PositionOf("EmployeeDepartmentAssignment"));

    Assert.True(PositionOf(nameof(Employee)) < PositionOf(nameof(EmployeeBranchAssignment)));
  }

  // ---- C6-14. AND THE OLD, CONTRIBUTOR-FREE MODEL DEMONSTRABLY DOES NOT.
  //
  // The regression detector. It proves the fix is load-bearing rather than incidental: without the
  // contributor set the manifest silently loses every HR table, which is exactly what shipped before this
  // slice. If these two ever agreed, the composition would have collapsed back and every proof below would
  // still pass while production quietly lost data again.
  //
  // FP-007 Phase 1 made the gap wider rather than different — five HR tables now, not two — which is the
  // point: each new contributed entity increases what a contributor-free manifest would silently leave
  // behind.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public void C6_14_A_contributor_free_plan_silently_omits_both_hr_tables()
  {
    var composed = TenantCutoverCopyPlan.Build(CutoverTenantModel.Source.Model);
    var contributorFree = TenantCutoverCopyPlan.Build(CutoverTenantModel.ContributorFreeSource.Model);

    Assert.True(composed.IsSuccess);

    // It SUCCEEDS. That is the danger: an incomplete manifest is not an error, it is a shorter list.
    Assert.True(contributorFree.IsSuccess);

    Assert.DoesNotContain(contributorFree.Value, table => table.EntityName == nameof(Employee));
    Assert.DoesNotContain(
      contributorFree.Value, table => table.EntityName == nameof(EmployeeBranchAssignment));
    Assert.DoesNotContain(contributorFree.Value, table => table.EntityName == "Department");
    Assert.DoesNotContain(contributorFree.Value, table => table.EntityName == "DepartmentManager");
    Assert.DoesNotContain(
      contributorFree.Value, table => table.EntityName == "EmployeeDepartmentAssignment");

    // Five HR tables missing, and only Platform's Company and Branch left.
    Assert.Equal(
      composed.Value.Count - 5,
      contributorFree.Value.Count);
    Assert.Equal(2, contributorFree.Value.Count);
  }

  // ---- C6-6 / C6-11. DEPENDENCY ORDER, DERIVED FROM FOREIGN KEYS.
  //
  // Employee references Company and Branch; the assignment references Employee. Inserting a dependent
  // before its principal would violate referential integrity with constraints ON, which the engine keeps on
  // throughout — so the order is a correctness requirement, not a preference.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public void C6_6_Employee_is_ordered_after_company_and_branch_and_history_after_employee()
  {
    var plan = TenantCutoverCopyPlan.Build(CutoverTenantModel.Source.Model);
    Assert.True(plan.IsSuccess);

    var order = plan.Value.Select(table => table.EntityName).ToArray();

    var company = Array.IndexOf(order, nameof(Company));
    var branch = Array.IndexOf(order, nameof(Branch));
    var employee = Array.IndexOf(order, nameof(Employee));
    var history = Array.IndexOf(order, nameof(EmployeeBranchAssignment));

    Assert.True(employee > company, $"Employee must follow Company. Order: {string.Join(", ", order)}");
    Assert.True(employee > branch, $"Employee must follow Branch. Order: {string.Join(", ", order)}");
    Assert.True(history > employee, $"History must follow Employee. Order: {string.Join(", ", order)}");

    // ---- AND THE ORDER IS PRODUCED BY THE FK GRAPH, NOT BY THE NAMES.
    //
    // "EmployeeBranchAssignments" sorts BEFORE "Employees" alphabetically, so an alphabetical ordering would
    // place the dependent first. That it does not is the proof the topological sort is doing the work.
    Assert.True(
      string.CompareOrdinal("EmployeeBranchAssignments", "Employees") < 0,
      "The premise of this assertion no longer holds.");
  }

  // ---- C6-12. THE HISTORY STILL CARRIES NO BRANCH FOREIGN KEY.
  //
  // ADR-024 classifies the assignment as company-owned but NOT branch-owned: it names a source and a
  // destination and belongs to neither. Adding a branch FK would have made the copy ordering marginally
  // easier to reason about and would have broken that classification, so it was not done — and this records
  // that the convenience was declined.
  [Fact]
  [Trait("Decision", "ADR-024")]
  public void C6_12_The_assignment_has_no_branch_foreign_key()
  {
    var assignment = CutoverTenantModel.Source.Model.FindEntityType(typeof(EmployeeBranchAssignment));
    Assert.NotNull(assignment);

    var principals = assignment!.GetForeignKeys()
      .Select(foreignKey => foreignKey.PrincipalEntityType.ClrType.Name)
      .ToArray();

    Assert.DoesNotContain(nameof(Branch), principals);
    Assert.Contains(nameof(Employee), principals);
  }

  // ---- C6-7. ROWVERSION IS NOT CARRIED ACROSS.
  //
  // It is the TARGET's concurrency state, generated by the target on insert. Copying the source's bytes
  // would hand the new database a token describing a different database's history.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public void C6_7_The_employee_rowversion_is_excluded_from_the_copy_projection()
  {
    var plan = TenantCutoverCopyPlan.Build(CutoverTenantModel.Source.Model);
    var employees = Assert.Single(plan.Value, table => table.EntityName == nameof(Employee));

    // A live exclusion: Employee genuinely carries a rowversion, so this is not vacuous.
    var model = CutoverTenantModel.Source.Model.FindEntityType(typeof(Employee));
    Assert.Contains(
      model!.GetProperties(),
      property => property.IsConcurrencyToken && property.ValueGenerated == ValueGenerated.OnAddOrUpdate);

    Assert.DoesNotContain(nameof(Employee.RowVersion), employees.Columns);

    // The assignment carries none at all — it is append-only and never updated — so there is nothing to
    // exclude and nothing to transport.
    var assignments = Assert.Single(
      plan.Value, table => table.EntityName == nameof(EmployeeBranchAssignment));

    Assert.DoesNotContain("RowVersion", assignments.Columns);
  }

  // ================================================================================================
  // C6-3 / C6-4 / C6-5 / C6-8 / C6-9 / C6-10 — THE REAL CUTOVER.
  // ================================================================================================
  //
  // One tenant with a full transfer story is promoted while a second tenant sharing the same physical
  // database is not. Everything below is read back from the destination database with raw SQL.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task C6_3_To_C6_10_A_real_cutover_carries_the_employee_and_its_whole_history()
  {
    await using var fixture = await CopyFixture.CreateAsync();

    var moving = await fixture.SeedEmployeeStoryAsync(fixture.TenantA, "MOV");

    // ---- THE LEAKAGE CONTROL, SEEDED FIRST AND IN THE SAME TABLES.
    //
    // A co-tenant with its own company, branches, employee and history, sharing the physical source
    // database. Without it, "the destination contains the right rows" would also be true of a copy that
    // took everything.
    var staying = await fixture.SeedEmployeeStoryAsync(fixture.TenantB, "STAY");

    var operationId = await fixture.BeginAndFreezeAsync();

    // Push the TARGET's rowversion counter past anything the source could hold, so the rowversion assertion
    // below is deterministic rather than a coincidence of two fresh databases.
    await fixture.AdvanceTargetRowVersionCounterAsync();
    var watermark = await fixture.TargetRowVersionWatermarkAsync();

    Assert.True(
      Counter((await fixture.SourceEmployeesAsync(fixture.TenantA)).Single().RowVersion) < watermark,
      "the source counter is not below the target watermark, so this test would prove nothing");

    var copied = await fixture.CopyService().CopyAsync(operationId);

    Assert.True(copied.IsSuccess, copied.IsFailure ? copied.Error.Code : null);

    // SEVEN TABLES, not two. This count is the headline regression: before FP-006C6 it was two, and the
    // difference was every employee in the tenant. FP-007 Phase 1 took it to seven, and the three added
    // names below are the live proof that a Shared→Dedicated cutover carries Departments — the property
    // ADR-026 decision 7 exists to guarantee, and the reason DepartmentManager is its own table rather than
    // a column that would have made the copy order undecidable.
    Assert.Equal(7, copied.Value.TablesCopied);
    Assert.Equal(
      [
        nameof(Branch),
        nameof(Company),
        "Department",
        "DepartmentManager",
        nameof(Employee),
        nameof(EmployeeBranchAssignment),
        "EmployeeDepartmentAssignment"
      ],
      copied.Value.Tables.Select(table => table.EntityName).OrderBy(name => name, StringComparer.Ordinal));

    // ---- C6-3. THE EMPLOYEE ARRIVED.
    var targetEmployees = await fixture.TargetEmployeesAsync(fixture.TenantA);
    var employee = Assert.Single(targetEmployees);

    // ---- C6-8. IDENTIFIERS PRESERVED, never regenerated: every reference to this employee elsewhere in
    // the estate would otherwise point at nothing.
    Assert.Equal(moving.EmployeeId, employee.EmployeeId);
    Assert.Equal(moving.EmployeeNumber, employee.EmployeeNumber);

    // ---- C6-9 / C6-11. CURRENT OWNERSHIP PRESERVED, and pointing at rows that were themselves copied.
    Assert.Equal(moving.CompanyId, employee.CompanyId);
    Assert.Equal(moving.DestinationBranchId, employee.BranchId);
    Assert.Equal(fixture.TenantA, employee.TenantId);

    // ---- C6-7, ON REAL DATA. The destination generated its own token.
    //
    // "source bytes != target bytes" is NOT a proof — rowversion is a per-database counter, and two freshly
    // created databases can legitimately issue identical values. The deterministic proof is the watermark
    // pushed past anything the source could hold before the copy ran: a token carried over from the source
    // would necessarily fall below it.
    Assert.Equal(8, employee.RowVersion.Length);
    Assert.True(
      Counter(employee.RowVersion) > watermark,
      "the employee's rowversion is at or below the pre-copy target watermark, so it was carried over.");

    // ---- C6-4. THE WHOLE HISTORY ARRIVED, in order, with its data intact.
    var history = await fixture.TargetAssignmentsAsync(fixture.TenantA);

    Assert.Equal(2, history.Count);
    Assert.Equal([moving.InitialAssignmentId, moving.TransferAssignmentId],
      history.Select(row => row.AssignmentId));

    // The initial record names where employment STARTED and has no source.
    Assert.Null(history[0].SourceBranchId);
    Assert.Equal(moving.SourceBranchId, history[0].DestinationBranchId);
    Assert.Equal("InitialAssignment", history[0].ReasonCode);

    Assert.Equal(moving.SourceBranchId, history[1].SourceBranchId);
    Assert.Equal(moving.DestinationBranchId, history[1].DestinationBranchId);
    Assert.Equal("Reorganisation", history[1].ReasonCode);

    // ---- C6-10. POINT-IN-TIME ATTRIBUTION SURVIVES THE MOVE.
    //
    // The greatest EffectiveFromUtc at or before T, computed identically on both sides. This is the proof
    // that matters most for reporting: an employee's branch on a past date must not change because the
    // tenant was promoted.
    var sourceHistory = await fixture.SourceAssignmentsAsync(fixture.TenantA);

    foreach (var instant in new[]
    {
      moving.InitialEffectiveUtc,
      moving.TransferEffectiveUtc.AddTicks(-1),
      moving.TransferEffectiveUtc,
      moving.TransferEffectiveUtc.AddDays(1)
    })
    {
      Assert.Equal(BranchAt(sourceHistory, instant), BranchAt(history, instant));
    }

    // And it is a real comparison: the answer genuinely differs across the transfer instant, so identical
    // results are not identical because everything answers the same.
    Assert.NotEqual(
      BranchAt(history, moving.TransferEffectiveUtc.AddTicks(-1)),
      BranchAt(history, moving.TransferEffectiveUtc));

    // ---- C6-5. THE CO-TENANT DID NOT TRAVEL.
    Assert.Empty(await fixture.TargetEmployeesAsync(fixture.TenantB));
    Assert.Empty(await fixture.TargetAssignmentsAsync(fixture.TenantB));

    // Nothing else arrived either — the destination holds this tenant's rows and no others.
    Assert.Single(await fixture.TargetEmployeesAsync(null));
    Assert.Equal(2, (await fixture.TargetAssignmentsAsync(null)).Count);

    // ---- AND THE SOURCE IS UNCHANGED. A copy is not a move.
    Assert.Single(await fixture.SourceEmployeesAsync(fixture.TenantA));
    Assert.Single(await fixture.SourceEmployeesAsync(fixture.TenantB));
    Assert.Equal(staying.EmployeeId, (await fixture.SourceEmployeesAsync(fixture.TenantB)).Single().EmployeeId);
  }

  // ---- RESUME. THE HR TABLES PARTICIPATE IN IDEMPOTENT RE-RUN.
  //
  // Cutover copy is resumable: a second run must prove each table already complete rather than duplicate it.
  // Adding two tables to the manifest must not create two tables that re-copy on retry.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task C6_Retrying_a_completed_copy_verifies_the_hr_tables_instead_of_duplicating_them()
  {
    await using var fixture = await CopyFixture.CreateAsync();
    await fixture.SeedEmployeeStoryAsync(fixture.TenantA, "RTY");
    var operationId = await fixture.BeginAndFreezeAsync();

    Assert.True((await fixture.CopyService().CopyAsync(operationId)).IsSuccess);

    var retried = await fixture.CopyService().CopyAsync(operationId);

    Assert.True(retried.IsSuccess, retried.IsFailure ? retried.Error.Code : null);

    // EVERY ROW-BEARING table already complete, including the HR tables — nothing copied twice.
    //
    // FIVE complete and TWO recopied, not seven complete. Company, Branch, Employee,
    // EmployeeBranchAssignment and Department all hold rows in this fixture; DepartmentManagers and
    // EmployeeDepartmentAssignments are empty, and an empty table is indistinguishable from one that was
    // never copied, so the engine copies each again and moves nothing — the same rule the retry test above
    // states. The claim this test makes is that rows are never DUPLICATED, and the destination counts below
    // are what prove it; a table count of seven here would assert something the engine has never promised.
    //
    // Department joined the row-bearing set when FP-007 Phase 3 made Employee.DepartmentId a required
    // foreign key: the fixture must seed a real department before it can seed an employee at all.
    Assert.Equal(5, retried.Value.TablesAlreadyComplete);
    Assert.Equal(2, retried.Value.TablesCopied);

    // And the destination still holds exactly one of each, so "already complete" was a verification rather
    // than a shrug.
    Assert.Single(await fixture.TargetEmployeesAsync(fixture.TenantA));
    Assert.Equal(2, (await fixture.TargetAssignmentsAsync(fixture.TenantA)).Count);
  }

  // ---- COUNTS ARE COMPARED, NOT ASSUMED.
  //
  // A successful SQL command is not a copy. Source and destination row counts must agree for both HR tables
  // as well as Platform's.
  [Fact]
  [Trait("Decision", "ADR-020")]
  public async Task C6_Source_and_destination_counts_agree_for_both_hr_tables()
  {
    await using var fixture = await CopyFixture.CreateAsync();
    await fixture.SeedEmployeeStoryAsync(fixture.TenantA, "CNT");
    await fixture.SeedEmployeeStoryAsync(fixture.TenantB, "OTH");
    var operationId = await fixture.BeginAndFreezeAsync();

    Assert.True((await fixture.CopyService().CopyAsync(operationId)).IsSuccess);

    Assert.Equal(
      (await fixture.SourceEmployeesAsync(fixture.TenantA)).Count,
      (await fixture.TargetEmployeesAsync(fixture.TenantA)).Count);

    Assert.Equal(
      (await fixture.SourceAssignmentsAsync(fixture.TenantA)).Count,
      (await fixture.TargetAssignmentsAsync(fixture.TenantA)).Count);

    // The co-tenant's rows are counted on the source and absent from the destination, which is what makes
    // the equality above a scoped equality rather than a total one.
    Assert.NotEmpty(await fixture.SourceEmployeesAsync(fixture.TenantB));
    Assert.Empty(await fixture.TargetEmployeesAsync(fixture.TenantB));
  }

  // The point-in-time primitive, computed the same way on both databases.
  private static Guid BranchAt(IReadOnlyList<AssignmentRow> history, DateTimeOffset at) =>
    history
      .Where(row => row.EffectiveFromUtc <= at)
      .OrderBy(row => row.EffectiveFromUtc)
      .ThenBy(row => row.AssignmentId)
      .Last()
      .DestinationBranchId;

  // Three real catalogs: the Platform registry, a SHARED source holding two tenants, and a DEDICATED
  // target. The separation is what makes "only tenant A moved" checkable by querying each catalog directly.
  private sealed class CopyFixture : IAsyncDisposable
  {
    private const string ServerKey = "PrimarySqlServer";
    private const string Actor = "cutover-copy-tests";

    private static readonly DateTimeOffset Now = new(2026, 8, 17, 12, 0, 0, TimeSpan.Zero);

    private readonly string token = Guid.NewGuid().ToString("N")[..12];
    private readonly TenantStorageOptions storage = new();
    private readonly TenantCutoverFreezeOptions freeze = new();
    private readonly TenantCutoverCopyOptions copy = new();
    private string platformCatalog = string.Empty;

    public string SourceCatalog { get; private set; } = string.Empty;

    public string TargetCatalog { get; private set; } = string.Empty;

    public Guid TenantA { get; private set; }

    public Guid TenantB { get; private set; }

    public long SourceDatabaseId { get; private set; }

    public long TargetDatabaseId { get; private set; }

    public long SecondSharedDatabaseId { get; private set; }

    public string PlatformConnectionString => ConnectionFor(platformCatalog);

    public static async Task<CopyFixture> CreateAsync(bool migrateTarget = true)
    {
      var fixture = new CopyFixture();
      try
      {
        await fixture.InitialiseAsync(migrateTarget);
        return fixture;
      }
      catch
      {
        await fixture.DisposeAsync();
        throw;
      }
    }

    private async Task InitialiseAsync(bool migrateTarget)
    {
      platformCatalog = $"SSAS_E3_Platform_{token}";
      SourceCatalog = $"SSAS_E3_Shared_{token}";
      TargetCatalog = $"SSAS_E3_Dedicated_{token}";
      freeze.WriteAdmissionTimeout = TimeSpan.FromSeconds(2);

      foreach (var catalog in new[] { platformCatalog, SourceCatalog, TargetCatalog })
      {
        await ExecuteAsync("master", $"CREATE DATABASE [{catalog}]");
      }

      await MigrateTenantAsync(SourceCatalog);
      if (migrateTarget)
      {
        await MigrateTenantAsync(TargetCatalog);
      }

      storage.Servers[ServerKey] = new TenantStorageServerOptions { ConnectionString = Configured() };

      await using var platform = PlatformContext();
      await platform.Database.MigrateAsync();

      SourceDatabaseId = await RegisterAsync(
        platform, TenantDatabaseStorageMode.Shared, SourceCatalog);
      TargetDatabaseId = await RegisterAsync(
        platform, TenantDatabaseStorageMode.Dedicated, TargetCatalog);
      SecondSharedDatabaseId = await RegisterAsync(
        platform, TenantDatabaseStorageMode.Shared, $"SSAS_E3_SharedTwo_{token}");

      TenantA = await SeedTenantAsync(platform, "E3AAA");
      TenantB = await SeedTenantAsync(platform, "E3BBB");
    }

    private static async Task MigrateTenantAsync(string catalog)
    {
      await using var connection = new SqlConnection(ConnectionFor(catalog));
      var options = new DbContextOptionsBuilder<TenantDbContext>()
        .UseSqlServer(connection, sql => sql.MigrationsHistoryTable(
          TenantPersistenceConstants.MigrationHistoryTable,
          TenantPersistenceConstants.MigrationHistorySchema))
        .Options;
      await using var context = new TenantDbContext(
        options, new TestUser(), new TestTenant(null), new TestClock());
      await context.Database.MigrateAsync();
    }

    private static async Task<long> RegisterAsync(
      PlatformDbContext platform, TenantDatabaseStorageMode storageMode, string databaseName)
    {
      var database = TenantDatabase.Register(
        TenantDatabaseHostingMode.PlatformManaged, storageMode, ServerKey, databaseName,
        TenantDatabaseProvisioningStatus.Ready, Actor, Now).Value;
      database.RecordConnectivity(TenantDatabaseConnectivityStatus.Healthy, Actor, Now);
      database.RecordSchemaHealth(
        TenantDatabaseSchemaCompatibilityStatus.UpToDate, null, null, Actor, Now);
      platform.TenantDatabases.Add(database);
      await platform.SaveChangesAsync();
      return database.Id;
    }

    private async Task<Guid> SeedTenantAsync(PlatformDbContext platform, string code)
    {
      var tenant = Tenant.Create(
        TenantCode.Create(code).Value, TenantName.Create($"Phase E3 {code}").Value,
        Actor, Guid.NewGuid(), Now).Value;
      platform.Tenants.Add(tenant);
      await platform.SaveChangesAsync();

      platform.TenantDatabaseAssignments.Add(
        TenantDatabaseAssignment.CreateInitial(tenant.Id, SourceDatabaseId, "phase-e3", Actor, Now).Value);
      await platform.SaveChangesAsync();
      return tenant.Id;
    }

    public TenantCutoverOperationStore Store() =>
      new(PlatformContext(), new TestClock(), copy.ReleaseOwnershipTimeout);

    public TenantCutoverFreezeService FreezeService()
    {
      var platform = PlatformContext();
      return new TenantCutoverFreezeService(
        new TenantCutoverOperationStore(platform, new TestClock(), copy.ReleaseOwnershipTimeout),
        new SSAS.Platform.Application.TenantStorage.TenantDatabaseResolver(
          new SSAS.Platform.Infrastructure.Persistence.Repositories.TenantDatabaseRegistryReadRepository(platform)),
        ConnectionFactory(),
        Options.Create(freeze));
    }

    public TenantCutoverCopyService CopyService()
    {
      var platform = PlatformContext();
      return new TenantCutoverCopyService(
        new TenantCutoverOperationStore(platform, new TestClock(), copy.ReleaseOwnershipTimeout),
        ConnectionFactory(),
        platform,
        Options.Create(copy),
        // THE HR-COMPOSED TENANT MODEL, exactly as the Host registers it (FP-006C6). Passing the
        // contributor-free model here would test a cutover that cannot see Employee — which is precisely
        // the defect this slice closes.
        CutoverTenantModel.Source);
    }

    private TenantDatabaseConnectionFactory ConnectionFactory() => new(Options.Create(storage));

    // The real fenced write boundary against the shared source.
    public TenantDbContext SourceTenantContext(Guid tenantId)
    {
      var options = new DbContextOptionsBuilder<TenantDbContext>()
        .UseSqlServer(new SqlConnection(ConnectionFor(SourceCatalog)), contextOwnsConnection: true,
          sql => sql.MigrationsHistoryTable(
            TenantPersistenceConstants.MigrationHistoryTable,
            TenantPersistenceConstants.MigrationHistorySchema))
        .Options;
      return new TenantDbContext(
        options, new TestUser(), new TestTenant(tenantId), new TestClock(),
        new TenantCutoverWriteFence(Store(), Options.Create(freeze)));
    }

    public async Task<long> BeginAsync()
    {
      var begun = await Store().BeginAsync(
        new TenantCutoverBeginRequest(TenantA, SourceDatabaseId, TargetDatabaseId, Actor));
      Assert.True(begun.IsSuccess);
      return begun.Value;
    }

    public async Task<long> BeginAndFreezeAsync()
    {
      var operationId = await BeginAsync();
      Assert.True((await FreezeService().FreezeAsync(operationId)).IsSuccess);
      return operationId;
    }

    public async Task<TenantCutoverOperationRecord> ReadAsync(long operationId)
    {
      var operation = await Store().FindAsync(operationId);
      Assert.NotNull(operation);
      return operation!;
    }

    public static Company NewCompany(Guid tenantId, string code) =>
      Company.Create(
        tenantId, CompanyCode.Create(code).Value, CompanyName.Create($"Company {code}").Value,
        BaseCurrencyCode.Create("USD").Value, Actor, Guid.NewGuid(), Now).Value;

    // ================================================================================================
    // HR SEEDING, FOR THE FP-006C6 CUTOVER PROOFS.
    // ================================================================================================
    //
    // Raw SQL for the same reason the Company seed uses it: this is arranging a SOURCE database, and going
    // through the write path would make every arrange step depend on the freeze and the authorizers under
    // test. The rows are shaped exactly as the C3 write path produces them.
    //
    // The transfer story is seeded in full — a company, two branches, an employee currently in the second,
    // an initial assignment naming the first, and a transfer assignment between them — because the
    // point-in-time attribution proof needs a history with more than one row in it to mean anything.
    public async Task<EmployeeStory> SeedEmployeeStoryAsync(Guid tenantId, string prefix)
    {
      var story = new EmployeeStory(
        Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(),
        Guid.NewGuid(),
        $"{prefix}-EMP-1", Now.AddDays(-30), Now.AddDays(-10));

      await using var connection = new SqlConnection(ConnectionFor(SourceCatalog));
      await connection.OpenAsync();
      await using var transaction = (SqlTransaction)await connection.BeginTransactionAsync();

      await ExecuteAsync(connection, transaction, """
        INSERT INTO [tenant].[Companies]
          ([CompanyId], [TenantId], [CompanyCode], [NormalizedCompanyCode], [CompanyName],
           [BaseCurrencyCode], [Status], [StatusChangeReasonCode], [StatusChangedUtc], [StatusChangedBy],
           [CreatedUtc], [CreatedBy], [ModifiedUtc], [ModifiedBy])
        VALUES
          (@CompanyId, @TenantId, @Code, @Code, @Name, 'USD', N'Active', N'Created', @Stamp, @Actor,
           @Stamp, @Actor, @Stamp, @Actor);
        """,
        ("@CompanyId", story.CompanyId), ("@TenantId", tenantId), ("@Code", $"{prefix}CO"),
        ("@Name", $"Company {prefix}"), ("@Stamp", Now.UtcDateTime), ("@Actor", Actor));

      foreach (var (branchId, code, isMain) in new[]
      {
        (story.SourceBranchId, $"{prefix}B1", true),
        (story.DestinationBranchId, $"{prefix}B2", false)
      })
      {
        await ExecuteAsync(connection, transaction, """
          INSERT INTO [tenant].[Branches]
            ([BranchId], [TenantId], [BranchCode], [NormalizedBranchCode], [BranchName], [IsMainBranch],
             [IsActive], [CreatedUtc], [CreatedBy], [ModifiedUtc], [ModifiedBy])
          VALUES
            (@BranchId, @TenantId, @Code, @Code, @Name, @IsMain, 1, @Stamp, @Actor, @Stamp, @Actor);
          """,
          ("@BranchId", branchId), ("@TenantId", tenantId), ("@Code", code), ("@Name", $"Branch {code}"),
          ("@IsMain", isMain), ("@Stamp", Now.UtcDateTime), ("@Actor", Actor));
      }

      // ---- THE DEPARTMENT THE EMPLOYEE BELONGS TO (FP-007 Phase 3).
      //
      // Seeded BEFORE the employee, because DepartmentId is NOT NULL with a restricted foreign key — which
      // is also why the copy engine must now order Departments ahead of Employees. That ordering is derived
      // from the model rather than declared, so this row is what makes the derivation observable: if the
      // plan ever emitted Employees first, the copy would fail on this constraint rather than silently
      // producing a wrong result.
      await ExecuteAsync(connection, transaction, """
        INSERT INTO [tenant].[Departments]
          ([DepartmentId], [TenantId], [CompanyId], [Code], [NormalizedCode], [Name], [ParentDepartmentId],
           [Status], [StatusChangedUtc], [StatusChangedBy], [CreatedUtc], [CreatedBy], [ModifiedUtc],
           [ModifiedBy])
        VALUES
          (@DepartmentId, @TenantId, @CompanyId, @Code, @Code, @Name, NULL,
           N'Active', @Stamp, @Actor, @Stamp, @Actor, @Stamp, @Actor);
        """,
        ("@DepartmentId", story.DepartmentId), ("@TenantId", tenantId), ("@CompanyId", story.CompanyId),
        ("@Code", $"{prefix}DEP"), ("@Name", $"Department {prefix}"),
        ("@Stamp", Now.UtcDateTime), ("@Actor", Actor));

      // The employee's CURRENT branch is the destination: they have already been transferred, which is what
      // makes "current branch preserved" and "historical attribution preserved" two different assertions.
      await ExecuteAsync(connection, transaction, """
        INSERT INTO [tenant].[Employees]
          ([EmployeeId], [TenantId], [CompanyId], [BranchId], [DepartmentId], [EmployeeNumber],
           [NormalizedEmployeeNumber], [FullName], [EmploymentDate], [Status], [StatusChangeReasonCode],
           [StatusChangedUtc], [StatusChangedBy], [CreatedUtc], [ModifiedUtc], [CreatedBy], [ModifiedBy])
        VALUES
          (@EmployeeId, @TenantId, @CompanyId, @BranchId, @DepartmentId, @Number, @Number, @Name,
           @Employment, N'Active', N'Created', @Stamp, @Actor, @Stamp, @Stamp, @Actor, @Actor);
        """,
        ("@EmployeeId", story.EmployeeId), ("@TenantId", tenantId), ("@CompanyId", story.CompanyId),
        ("@BranchId", story.DestinationBranchId), ("@DepartmentId", story.DepartmentId),
        ("@Number", story.EmployeeNumber),
        ("@Name", $"Person {prefix}"), ("@Employment", story.InitialEffectiveUtc.UtcDateTime),
        ("@Stamp", Now.UtcDateTime), ("@Actor", Actor));

      await ExecuteAsync(connection, transaction, """
        INSERT INTO [tenant].[EmployeeBranchAssignments]
          ([EmployeeBranchAssignmentId], [TenantId], [CompanyId], [EmployeeId], [SourceBranchId],
           [DestinationBranchId], [EffectiveFromUtc], [TransferredBy], [ReasonCode], [ReasonText],
           [CreatedUtc], [CreatedBy])
        VALUES
          (@Id, @TenantId, @CompanyId, @EmployeeId, NULL, @Destination, @Effective, @Actor,
           N'InitialAssignment', NULL, @Stamp, @Actor);
        """,
        ("@Id", story.InitialAssignmentId), ("@TenantId", tenantId), ("@CompanyId", story.CompanyId),
        ("@EmployeeId", story.EmployeeId), ("@Destination", story.SourceBranchId),
        ("@Effective", story.InitialEffectiveUtc.UtcDateTime), ("@Stamp", Now.UtcDateTime), ("@Actor", Actor));

      await ExecuteAsync(connection, transaction, """
        INSERT INTO [tenant].[EmployeeBranchAssignments]
          ([EmployeeBranchAssignmentId], [TenantId], [CompanyId], [EmployeeId], [SourceBranchId],
           [DestinationBranchId], [EffectiveFromUtc], [TransferredBy], [ReasonCode], [ReasonText],
           [CreatedUtc], [CreatedBy])
        VALUES
          (@Id, @TenantId, @CompanyId, @EmployeeId, @Source, @Destination, @Effective, @Actor,
           N'Reorganisation', @Reason, @Stamp, @Actor);
        """,
        ("@Id", story.TransferAssignmentId), ("@TenantId", tenantId), ("@CompanyId", story.CompanyId),
        ("@EmployeeId", story.EmployeeId), ("@Source", story.SourceBranchId),
        ("@Destination", story.DestinationBranchId), ("@Effective", story.TransferEffectiveUtc.UtcDateTime),
        ("@Reason", "consolidating"), ("@Stamp", Now.UtcDateTime), ("@Actor", Actor));

      await transaction.CommitAsync();

      return story;
    }

    private static async Task ExecuteAsync(
      SqlConnection connection, SqlTransaction transaction, string sql,
      params (string Name, object Value)[] parameters)
    {
      await using var command = connection.CreateCommand();
      command.Transaction = transaction;
      command.CommandText = sql;

      foreach (var (name, value) in parameters)
      {
        command.Parameters.AddWithValue(name, value);
      }

      await command.ExecuteNonQueryAsync();
    }

    public Task<IReadOnlyList<EmployeeRow>> SourceEmployeesAsync(Guid? tenantId) =>
      ReadEmployeesAsync(SourceCatalog, tenantId);

    public Task<IReadOnlyList<EmployeeRow>> TargetEmployeesAsync(Guid? tenantId) =>
      ReadEmployeesAsync(TargetCatalog, tenantId);

    public Task<IReadOnlyList<AssignmentRow>> SourceAssignmentsAsync(Guid? tenantId) =>
      ReadAssignmentsAsync(SourceCatalog, tenantId);

    public Task<IReadOnlyList<AssignmentRow>> TargetAssignmentsAsync(Guid? tenantId) =>
      ReadAssignmentsAsync(TargetCatalog, tenantId);

    private static async Task<IReadOnlyList<EmployeeRow>> ReadEmployeesAsync(string catalog, Guid? tenantId)
    {
      await using var connection = new SqlConnection(ConnectionFor(catalog));
      await connection.OpenAsync();
      await using var command = connection.CreateCommand();
      command.CommandText = tenantId is null
        ? "SELECT [EmployeeId], [TenantId], [CompanyId], [BranchId], [EmployeeNumber], [RowVersion] FROM [tenant].[Employees] ORDER BY [EmployeeId];"
        : "SELECT [EmployeeId], [TenantId], [CompanyId], [BranchId], [EmployeeNumber], [RowVersion] FROM [tenant].[Employees] WHERE [TenantId] = @TenantId ORDER BY [EmployeeId];";

      if (tenantId is { } value)
      {
        command.Parameters.AddWithValue("@TenantId", value);
      }

      var rows = new List<EmployeeRow>();
      await using var reader = await command.ExecuteReaderAsync();
      while (await reader.ReadAsync())
      {
        rows.Add(new EmployeeRow(
          reader.GetGuid(0), reader.GetGuid(1), reader.GetGuid(2), reader.GetGuid(3),
          reader.GetString(4), (byte[])reader[5]));
      }

      return rows;
    }

    private static async Task<IReadOnlyList<AssignmentRow>> ReadAssignmentsAsync(string catalog, Guid? tenantId)
    {
      await using var connection = new SqlConnection(ConnectionFor(catalog));
      await connection.OpenAsync();
      await using var command = connection.CreateCommand();
      command.CommandText = tenantId is null
        ? "SELECT [EmployeeBranchAssignmentId], [TenantId], [EmployeeId], [SourceBranchId], [DestinationBranchId], [EffectiveFromUtc], [ReasonCode] FROM [tenant].[EmployeeBranchAssignments] ORDER BY [EffectiveFromUtc], [EmployeeBranchAssignmentId];"
        : "SELECT [EmployeeBranchAssignmentId], [TenantId], [EmployeeId], [SourceBranchId], [DestinationBranchId], [EffectiveFromUtc], [ReasonCode] FROM [tenant].[EmployeeBranchAssignments] WHERE [TenantId] = @TenantId ORDER BY [EffectiveFromUtc], [EmployeeBranchAssignmentId];";

      if (tenantId is { } value)
      {
        command.Parameters.AddWithValue("@TenantId", value);
      }

      var rows = new List<AssignmentRow>();
      await using var reader = await command.ExecuteReaderAsync();
      while (await reader.ReadAsync())
      {
        rows.Add(new AssignmentRow(
          reader.GetGuid(0), reader.GetGuid(1), reader.GetGuid(2),
          await reader.IsDBNullAsync(3) ? null : reader.GetGuid(3),
          reader.GetGuid(4), reader.GetDateTimeOffset(5), reader.GetString(6)));
      }

      return rows;
    }
    // Seeded through raw SQL rather than the fenced context: this is arranging a source database, and going
    // through the write path would make every arrange step depend on the freeze under test.
    public Task SeedCompaniesAsync(Guid tenantId, int count, string prefix) =>
      SeedCompaniesIntoAsync(SourceCatalog, tenantId, count, prefix);

    public Task SeedTargetCompaniesAsync(Guid tenantId, int count, string prefix) =>
      SeedCompaniesIntoAsync(TargetCatalog, tenantId, count, prefix);

    private static async Task SeedCompaniesIntoAsync(
      string catalog, Guid tenantId, int count, string prefix)
    {
      await using var connection = new SqlConnection(ConnectionFor(catalog));
      await connection.OpenAsync();
      await using var transaction = (SqlTransaction)await connection.BeginTransactionAsync();

      for (var index = 0; index < count; index++)
      {
        var code = $"{prefix}{index:D6}";
        await using var command = connection.CreateCommand();
        command.Transaction = transaction;
        command.CommandText = """
          INSERT INTO [tenant].[Companies]
            ([CompanyId], [TenantId], [CompanyCode], [NormalizedCompanyCode], [CompanyName],
             [BaseCurrencyCode], [Status], [StatusChangeReasonCode], [StatusChangedUtc], [StatusChangedBy],
             [CreatedUtc], [CreatedBy], [ModifiedUtc], [ModifiedBy])
          VALUES
            (@Id, @TenantId, @Code, @Code, @Name, 'USD', N'Active', N'Created', @Stamp, @Actor,
             @Stamp, @Actor, @Stamp, @Actor);
          """;
        command.Parameters.AddWithValue("@Id", Guid.NewGuid());
        command.Parameters.AddWithValue("@TenantId", tenantId);
        command.Parameters.AddWithValue("@Code", code);
        command.Parameters.AddWithValue("@Name", $"Company {code}");
        // Distinct per row so "audit values verbatim" is a real comparison rather than one constant.
        command.Parameters.AddWithValue("@Stamp", Now.AddSeconds(index).UtcDateTime);
        command.Parameters.AddWithValue("@Actor", $"seed-{index % 7}");
        await command.ExecuteNonQueryAsync();
      }

      await transaction.CommitAsync();
    }

    public static async Task<Dictionary<Guid, CompanyRow>> ReadCompaniesAsync(string catalog, Guid tenantId)
    {
      await using var connection = new SqlConnection(ConnectionFor(catalog));
      await connection.OpenAsync();
      await using var command = connection.CreateCommand();
      command.CommandText = """
        SELECT [CompanyId], [TenantId], [CompanyCode], [CreatedUtc], [CreatedBy], [ModifiedUtc],
               [ModifiedBy], [StatusChangedUtc], [StatusChangedBy], [RowVersion]
        FROM [tenant].[Companies] WHERE [TenantId] = @TenantId ORDER BY [CompanyId];
        """;
      command.Parameters.AddWithValue("@TenantId", tenantId);

      var rows = new Dictionary<Guid, CompanyRow>();
      await using var reader = await command.ExecuteReaderAsync();
      while (await reader.ReadAsync())
      {
        var rowVersion = (byte[])reader[9];
        rows[reader.GetGuid(0)] = new CompanyRow(
          reader.GetGuid(1), reader.GetString(2),
          reader.GetDateTimeOffset(3), reader.GetString(4),
          reader.GetDateTimeOffset(5), reader.GetString(6),
          reader.GetDateTimeOffset(7), reader.GetString(8), rowVersion);
      }

      return rows;
    }

    public Task<int> SourceCompanyCountAsync(Guid? tenantId) => CompanyCountAsync(SourceCatalog, tenantId);

    public Task<int> TargetCompanyCountAsync(Guid? tenantId) => CompanyCountAsync(TargetCatalog, tenantId);

    private static async Task<int> CompanyCountAsync(string catalog, Guid? tenantId)
    {
      await using var connection = new SqlConnection(ConnectionFor(catalog));
      await connection.OpenAsync();
      await using var command = connection.CreateCommand();
      command.CommandText = tenantId is null
        ? "SELECT COUNT(*) FROM [tenant].[Companies]"
        : "SELECT COUNT(*) FROM [tenant].[Companies] WHERE [TenantId] = @TenantId";
      if (tenantId is { } value)
      {
        command.Parameters.AddWithValue("@TenantId", value);
      }

      return Convert.ToInt32(await command.ExecuteScalarAsync(), CultureInfo.InvariantCulture);
    }

    // A MISSING ROW CANNOT BE PRODUCED NORMALLY: tenant.TR_Companies_PreventDelete refuses physical deletes,
    // which is precisely why the engine can never delete target data either. The trigger is suspended here
    // ONLY to manufacture the torn state a crashed writer or a restore could leave, on a throwaway test
    // catalog, and is restored immediately. No production code path does this — an architecture guard
    // asserts the engine's sources contain no DISABLE TRIGGER at all.
    public Task DeleteOneTargetCompanyAsync(Guid tenantId) => ExecuteAsync(
      TargetCatalog,
      "DISABLE TRIGGER [tenant].[TR_Companies_PreventDelete] ON [tenant].[Companies]; " +
      $"DELETE TOP (1) FROM [tenant].[Companies] WHERE [TenantId] = '{tenantId:D}'; " +
      "ENABLE TRIGGER [tenant].[TR_Companies_PreventDelete] ON [tenant].[Companies];");

    // Drives the target's rowversion counter well past the source's, so "the target generated this" becomes
    // a deterministic comparison rather than a coincidence.
    public Task AdvanceTargetRowVersionCounterAsync() => ExecuteAsync(TargetCatalog, """
      CREATE TABLE [tenant].[RowVersionProbe]([Id] int NOT NULL PRIMARY KEY, [Stamp] rowversion NOT NULL);
      DECLARE @i int = 0;
      WHILE @i < 2000 BEGIN
        INSERT INTO [tenant].[RowVersionProbe]([Id]) VALUES(@i);
        SET @i = @i + 1;
      END
      DROP TABLE [tenant].[RowVersionProbe];
      """);

    public async Task<ulong> TargetRowVersionWatermarkAsync()
    {
      await using var connection = new SqlConnection(ConnectionFor(TargetCatalog));
      await connection.OpenAsync();
      await using var command = connection.CreateCommand();
      command.CommandText = "SELECT @@DBTS";
      return System.Buffers.Binary.BinaryPrimitives.ReadUInt64BigEndian(
        (byte[])(await command.ExecuteScalarAsync())!);
    }

    // Deliberately NOT suppressing the trigger: this asserts it is live on the copied target.
    public Task AttemptTargetDeleteAsync(Guid tenantId) => ExecuteAsync(
      TargetCatalog,
      $"DELETE FROM [tenant].[Companies] WHERE [TenantId] = '{tenantId:D}'");

    // The other half of §17-O, and it needs no trigger surgery: an EXTRA row the source does not have.
    public Task AddExtraTargetCompanyAsync(Guid tenantId) =>
      SeedCompaniesIntoAsync(TargetCatalog, tenantId, 1, "EXTRA");

    // §15: the complete DML trigger inventory of the tenant schema, read from the server.
    public static async Task<List<(string Name, string Type, bool Disabled)>> TriggersAsync(string catalog)
    {
      await using var connection = new SqlConnection(ConnectionFor(catalog));
      await connection.OpenAsync();
      await using var command = connection.CreateCommand();
      command.CommandText = """
        SELECT t.[name],
               CASE WHEN t.[is_instead_of_trigger] = 1 THEN N'INSTEAD OF' ELSE N'AFTER' END + N' ' +
                 STUFF((SELECT N',' + te.[type_desc] FROM sys.trigger_events te
                        WHERE te.[object_id] = t.[object_id] FOR XML PATH('')), 1, 1, N''),
               t.[is_disabled]
        FROM sys.triggers t
        JOIN sys.objects o ON o.[object_id] = t.[parent_id]
        JOIN sys.schemas s ON s.[schema_id] = o.[schema_id]
        WHERE s.[name] = N'tenant'
        ORDER BY t.[name];
        """;

      var triggers = new List<(string, string, bool)>();
      await using var reader = await command.ExecuteReaderAsync();
      while (await reader.ReadAsync())
      {
        triggers.Add((reader.GetString(0), reader.GetString(1), reader.GetBoolean(2)));
      }

      return triggers;
    }

    public Task MutateOneTargetCompanyNameAsync(Guid tenantId) => ExecuteAsync(
      TargetCatalog,
      "UPDATE TOP (1) [tenant].[Companies] SET [CompanyName] = N'Tampered' " +
      $"WHERE [TenantId] = '{tenantId:D}'");

    public async Task<bool> TargetHasCompaniesTableAsync()
    {
      await using var connection = new SqlConnection(ConnectionFor(TargetCatalog));
      await connection.OpenAsync();
      await using var command = connection.CreateCommand();
      command.CommandText = "SELECT OBJECT_ID(N'[tenant].[Companies]')";
      return await command.ExecuteScalarAsync() is not (null or DBNull);
    }

    public async Task RepointAssignmentAsync(Guid tenantId, long tenantDatabaseId)
    {
      await using var platform = PlatformContext();
      var current = await platform.TenantDatabaseAssignments
        .SingleAsync(assignment => assignment.TenantId == tenantId && assignment.EndedUtc == null);
      Assert.True(current.End(Actor, Now.AddMinutes(1)).IsSuccess);
      platform.TenantDatabaseAssignments.Add(TenantDatabaseAssignment.Create(
        tenantId, tenantDatabaseId, current.RoutingVersion + 1, "phase-e3", Actor, Now.AddMinutes(1)).Value);
      await platform.SaveChangesAsync();
    }

    // ---- Probe tables for identity and foreign-key ordering.
    public static async Task CreateProbeTablesAsync(string catalog)
    {
      await ExecuteAsync(catalog, """
        CREATE TABLE [tenant].[ProbeParents](
          [ProbeParentId] bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
          [TenantId] uniqueidentifier NOT NULL,
          [Label] nvarchar(64) NOT NULL);
        CREATE TABLE [tenant].[ProbeChildren](
          [ProbeChildId] uniqueidentifier NOT NULL PRIMARY KEY,
          [TenantId] uniqueidentifier NOT NULL,
          [ProbeParentId] bigint NOT NULL,
          [Label] nvarchar(64) NOT NULL,
          CONSTRAINT [FK_ProbeChildren_ProbeParents] FOREIGN KEY ([ProbeParentId])
            REFERENCES [tenant].[ProbeParents]([ProbeParentId]));
        """);
    }

    public async Task SeedProbeDataAsync(Guid tenantId)
    {
      await using var connection = new SqlConnection(ConnectionFor(SourceCatalog));
      await connection.OpenAsync();

      for (var parent = 0; parent < 2; parent++)
      {
        await using var insertParent = connection.CreateCommand();
        insertParent.CommandText =
          "INSERT INTO [tenant].[ProbeParents]([TenantId],[Label]) VALUES(@TenantId,@Label); " +
          "SELECT CAST(SCOPE_IDENTITY() AS bigint);";
        insertParent.Parameters.AddWithValue("@TenantId", tenantId);
        insertParent.Parameters.AddWithValue("@Label", $"parent-{parent}");
        var parentId = Convert.ToInt64(await insertParent.ExecuteScalarAsync(), CultureInfo.InvariantCulture);

        for (var child = 0; child < 2; child++)
        {
          await using var insertChild = connection.CreateCommand();
          insertChild.CommandText =
            "INSERT INTO [tenant].[ProbeChildren]([ProbeChildId],[TenantId],[ProbeParentId],[Label]) " +
            "VALUES(@Id,@TenantId,@ParentId,@Label);";
          insertChild.Parameters.AddWithValue("@Id", Guid.NewGuid());
          insertChild.Parameters.AddWithValue("@TenantId", tenantId);
          insertChild.Parameters.AddWithValue("@ParentId", parentId);
          insertChild.Parameters.AddWithValue("@Label", $"child-{parent}-{child}");
          await insertChild.ExecuteNonQueryAsync();
        }
      }
    }

    public static async Task<List<long>> ProbeParentIdsAsync(string catalog, Guid tenantId)
    {
      await using var connection = new SqlConnection(ConnectionFor(catalog));
      await connection.OpenAsync();
      await using var command = connection.CreateCommand();
      command.CommandText =
        "SELECT [ProbeParentId] FROM [tenant].[ProbeParents] WHERE [TenantId] = @TenantId " +
        "ORDER BY [ProbeParentId]";
      command.Parameters.AddWithValue("@TenantId", tenantId);

      var ids = new List<long>();
      await using var reader = await command.ExecuteReaderAsync();
      while (await reader.ReadAsync())
      {
        ids.Add(reader.GetInt64(0));
      }

      return ids;
    }

    public static async Task<int> ProbeChildCountAsync(string catalog, Guid tenantId)
    {
      await using var connection = new SqlConnection(ConnectionFor(catalog));
      await connection.OpenAsync();
      await using var command = connection.CreateCommand();
      command.CommandText =
        "SELECT COUNT(*) FROM [tenant].[ProbeChildren] WHERE [TenantId] = @TenantId";
      command.Parameters.AddWithValue("@TenantId", tenantId);
      return Convert.ToInt32(await command.ExecuteScalarAsync(), CultureInfo.InvariantCulture);
    }

    public static async Task<int> OrphanedProbeChildCountAsync(string catalog)
    {
      await using var connection = new SqlConnection(ConnectionFor(catalog));
      await connection.OpenAsync();
      await using var command = connection.CreateCommand();
      command.CommandText = """
        SELECT COUNT(*) FROM [tenant].[ProbeChildren] c
        WHERE NOT EXISTS (SELECT 1 FROM [tenant].[ProbeParents] p
                          WHERE p.[ProbeParentId] = c.[ProbeParentId]);
        """;
      return Convert.ToInt32(await command.ExecuteScalarAsync(), CultureInfo.InvariantCulture);
    }

    // LOW-3 needs the write-fence lookup measured against a table that has ACCUMULATED, because that is what
    // it will face: every completed and abandoned cutover stays as history. Measuring it against one row —
    // as an unseeded fixture does — describes the fixture rather than the design.
    //
    // Abandoned rows are used because the filtered unique index admits only one ACTIVE operation per tenant,
    // which is exactly the property that keeps the hot lookup small no matter how much history exists.
    public Task SeedCutoverHistoryAsync(int count) => ExecuteAsync(platformCatalog, $"""
      DECLARE @i int = 0;
      WHILE @i < {count} BEGIN
        INSERT INTO [platform].[TenantCutoverOperations]
          ([TenantId],[SourceTenantDatabaseId],[TargetTenantDatabaseId],[Status],[StartedUtc],
           [CompletedUtc],[CreatedUtc],[CreatedBy],[ModifiedUtc],[ModifiedBy])
        VALUES
          (NEWID(), {SourceDatabaseId}, {TargetDatabaseId}, N'Abandoned', SYSDATETIMEOFFSET(),
           SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), N'history', SYSDATETIMEOFFSET(), N'history');
        SET @i = @i + 1;
      END
      """);

    // Statistics only. The procedure cache is deliberately NOT cleared any more: the plans are now returned
    // by the server rather than looked up in a cache, so emptying three caches would buy nothing. The target
    // catalog is not touched at all — it was only ever cleared, never measured.
    public async Task RefreshStatisticsAsync()
    {
      await ExecuteAsync(SourceCatalog, "UPDATE STATISTICS [tenant].[Companies] WITH FULLSCAN;");
      await ExecuteAsync(platformCatalog,
        "UPDATE STATISTICS [platform].[TenantCutoverOperations] WITH FULLSCAN;");
    }

    // Runs the two shapes under review once each, through the SAME code the engine and the fence use, so the
    // captured plans describe production queries rather than reconstructions of them.
    public async Task ReissueMeasuredQueriesAsync()
    {
      var plan = TenantCutoverCopyPlan.Build(CutoverTenantModel.Source.Model);

      // NAMED EXPLICITLY, not taken positionally. The manifest holds more than one table since Branch
      // foundation B0, and the shapes measured below are COMPANY's — the seeded, non-trivial table whose
      // plans this test exists to review. Picking whichever table happened to come first would silently
      // change what is being measured every time the model grows.
      var table = plan.Value.Single(candidate => candidate.EntityName == nameof(Company));
      var validator = new TenantCutoverCopyValidator(copy);

      await using var source = new SqlConnection(ConnectionFor(SourceCatalog));
      await source.OpenAsync();
      await validator.CountTenantRowsAsync(table, TenantA, source, null);

      // The engine's own source projection: tenant-filtered and primary-key ordered.
      await using var command = source.CreateCommand();
      command.CommandText =
        $"SELECT {table.ColumnList} FROM {table.QualifiedName} " +
        $"WHERE [{table.TenantIdColumn}] = @TenantId ORDER BY {table.OrderByPrimaryKey}";
      command.Parameters.Add("@TenantId", System.Data.SqlDbType.UniqueIdentifier).Value = TenantA;

      // Recorded here rather than by the EF interceptor, because this shape is issued over a raw connection
      // to the SOURCE catalog — it is the engine's own projection, built from the same copy-plan metadata,
      // so recording the command is recording production.
      sourceRead = new RecordedCommand(
        command.CommandText,
        command.Parameters
          .OfType<SqlParameter>()
          .Select(parameter => (SqlParameter)((ICloneable)parameter).Clone())
          .ToArray());

      await using (var reader = await command.ExecuteReaderAsync())
      {
        while (await reader.ReadAsync())
        {
        }
      }

      // LOW-3: the E1 write-fence lookup, through the real store.
      await Store().FindActiveWriteGateAsync(TenantA);
    }

    // Both shapes, replayed exactly as production issued them. The two live in DIFFERENT catalogs — the copy
    // source read against the tenant source, the fence lookup against the Platform registry — so each is
    // explained on its own connection rather than through one server-wide lookup that happened to see both.
    public async Task<IReadOnlyList<MeasuredPlan>> CapturePlansAsync() =>
    [
      await PlanAsync(
        "copy source read (tenant-filtered, PK-ordered)",
        ConnectionFor(SourceCatalog),
        sourceRead ?? throw new InvalidOperationException(
          "The copy source read was never issued; call ReissueMeasuredQueriesAsync first.")),

      // LOW-3: the write-fence lookup — "which cutover, if any, holds this tenant?". Identified by the
      // projection rather than by a keyword: since E4 the fence reads the operation's endpoints and
      // post-cutover observation instead of asking a yes/no question, so the shape changed with it.
      await PlanAsync(
        "cutover write-fence lookup",
        ConnectionFor(platformCatalog),
        recorder.Match(["[TenantCutoverOperations]", "[PostCutoverWriteObservedUtc]"])),
    ];

    private static async Task<MeasuredPlan> PlanAsync(
      string label, string connectionString, RecordedCommand recorded)
    {
      var captured = await QueryPlanCapture.ExplainAsync(connectionString, recorded);
      return new MeasuredPlan(label, captured.PlanXml, captured.LogicalReads, captured.Microseconds, 1);
    }

    // The recorder observes every statement the PRODUCTION components issue through this context; the copy
    // source read is captured separately because it runs over a raw connection. See QueryPlanCapture.
    private readonly ProductionSqlRecorder recorder = new();

    private RecordedCommand? sourceRead;

    private PlatformDbContext PlatformContext()
    {
      var options = new DbContextOptionsBuilder<PlatformDbContext>()
        .UseSqlServer(ConnectionFor(platformCatalog),
          sql => sql.MigrationsHistoryTable("__EFMigrationsHistory", "platform"))
        .AddInterceptors(recorder)
        .Options;
      return new PlatformDbContext(options, new TestUser(), new TestTenant(null), new TestClock());
    }

    private static string Configured() =>
      Environment.GetEnvironmentVariable("SSAS_TEST_SQLSERVER") ??
      "Server=localhost;Integrated Security=True;TrustServerCertificate=True;Encrypt=False";

    public static string ConnectionFor(string catalog) =>
      new SqlConnectionStringBuilder(Configured()) { InitialCatalog = catalog, Pooling = false }
        .ConnectionString;

    private static async Task ExecuteAsync(string catalog, string sql)
    {
      await using var connection = new SqlConnection(ConnectionFor(catalog));
      await connection.OpenAsync();
      await using var command = connection.CreateCommand();
      command.CommandText = sql;
      command.CommandTimeout = 600;
      await command.ExecuteNonQueryAsync();
    }

    public async ValueTask DisposeAsync()
    {
      foreach (var catalog in new[] { SourceCatalog, TargetCatalog, platformCatalog }
        .Where(value => !string.IsNullOrWhiteSpace(value)))
      {
        try
        {
          await ExecuteAsync("master",
            $"IF DB_ID(N'{catalog}') IS NOT NULL BEGIN " +
            $"ALTER DATABASE [{catalog}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; " +
            $"DROP DATABASE [{catalog}]; END");
        }
        catch (SqlException error)
        {
          TestCatalogJanitor.RecordLeak(catalog, error);
        }
      }
    }
  }

  private sealed record CompanyRow(
    Guid TenantId,
    string CompanyCode,
    DateTimeOffset CreatedUtc,
    string CreatedBy,
    DateTimeOffset ModifiedUtc,
    string ModifiedBy,
    DateTimeOffset StatusChangedUtc,
    string StatusChangedBy,
    byte[] RowVersion);

  // ---- The probe model: two tenant-owned entities with a real foreign key and a real identity key, so the
  // ordering and identity-preservation mechanisms are exercised rather than assumed.
  private sealed class ProbeParent : SSAS.BuildingBlocks.Domain.ITenantOwnedEntity
  {
    public long ProbeParentId { get; set; }
    public Guid TenantId { get; set; }
    public string Label { get; set; } = string.Empty;
  }

  private sealed class ProbeChild : SSAS.BuildingBlocks.Domain.ITenantOwnedEntity
  {
    public Guid ProbeChildId { get; set; }
    public Guid TenantId { get; set; }
    public long ProbeParentId { get; set; }
    public string Label { get; set; } = string.Empty;
  }

  private sealed class ProbeContext : DbContext
  {
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) =>
      optionsBuilder.UseSqlServer("Server=model-only;Database=model-only;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
      modelBuilder.Entity<ProbeParent>(entity =>
      {
        entity.ToTable("ProbeParents", "tenant");
        entity.HasKey(parent => parent.ProbeParentId);
        entity.Property(parent => parent.ProbeParentId).UseIdentityColumn();
        entity.Property(parent => parent.Label).HasMaxLength(64);
      });

      modelBuilder.Entity<ProbeChild>(entity =>
      {
        entity.ToTable("ProbeChildren", "tenant");
        entity.HasKey(child => child.ProbeChildId);
        entity.Property(child => child.Label).HasMaxLength(64);
        entity.HasOne<ProbeParent>()
          .WithMany()
          .HasForeignKey(child => child.ProbeParentId);
      });
    }
  }

  private sealed class TestUser : ICurrentUser
  {
    public string? UserId => "cutover-copy-tests";
    public string? UserName => null;
    public string? Email => null;
    public Guid? CompanyId => null;
    public string? SessionId => null;
    public string? TokenId => null;
    public IReadOnlyCollection<string> Roles => [];
    public IReadOnlyCollection<string> Permissions => [];
  }

  private sealed class TestTenant(Guid? tenantId) : ICurrentTenant
  {
    public Guid? TenantId => tenantId;
  }

  private sealed class TestClock : IDateTimeProvider
  {
    public DateTimeOffset UtcNow => new(2026, 8, 17, 12, 0, 0, TimeSpan.Zero);
  }
}

// The seeded transfer story, so a test can name the rows it expects rather than rediscovering them.
internal sealed record EmployeeStory(
  Guid CompanyId,
  Guid SourceBranchId,
  Guid DestinationBranchId,
  // FP-007 Phase 3: an employee has a department, and the cutover must carry it with everything else.
  Guid DepartmentId,
  Guid EmployeeId,
  Guid InitialAssignmentId,
  Guid TransferAssignmentId,
  string EmployeeNumber,
  DateTimeOffset InitialEffectiveUtc,
  DateTimeOffset TransferEffectiveUtc);

internal sealed record EmployeeRow(
  Guid EmployeeId, Guid TenantId, Guid CompanyId, Guid BranchId, string EmployeeNumber, byte[] RowVersion);

internal sealed record AssignmentRow(
  Guid AssignmentId,
  Guid TenantId,
  Guid EmployeeId,
  Guid? SourceBranchId,
  Guid DestinationBranchId,
  DateTimeOffset EffectiveFromUtc,
  string ReasonCode);
