// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSAS.Platform.Infrastructure.Persistence;

#nullable disable

namespace SSAS.Platform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260731200122_AddAuthenticationCredentialLifecycle")]
    partial class AddAuthenticationCredentialLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SSAS.Platform.Domain.Authentication.AccountActionToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AccountActionTokenId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthenticationAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ConsumedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("IdentityId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("IssuedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("RevokedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("TenantUserId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("secretHash")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("SecretHash")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("AuthenticationAccountId");

                    b.HasIndex("IdentityId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("secretHash")
                        .IsUnique();

                    b.HasIndex("Purpose", "AuthenticationAccountId")
                        .IsUnique()
                        .HasFilter("[ConsumedUtc] IS NULL AND [RevokedUtc] IS NULL AND [TenantUserId] IS NULL");

                    b.HasIndex("TenantId", "TenantUserId");

                    b.HasIndex("Purpose", "TenantId", "TenantUserId")
                        .IsUnique()
                        .HasFilter("[ConsumedUtc] IS NULL AND [RevokedUtc] IS NULL AND [TenantUserId] IS NOT NULL");

                    b.ToTable("AccountActionTokens", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_AccountActionTokens_Expiry", "[ExpiresUtc] > [IssuedUtc]");

                            t.HasCheckConstraint("CK_AccountActionTokens_OwnershipBinding", "([Purpose] = N'Invitation' AND [TenantId] IS NOT NULL AND [TenantUserId] IS NOT NULL) OR ([Purpose] = N'PasswordReset' AND [TenantId] IS NULL AND [TenantUserId] IS NULL)");
                        });
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Authentication.AuthenticationAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AuthenticationAccountId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EmailVerifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("int");

                    b.Property<long>("IdentityId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LockoutEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LoginEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedLoginEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset?>("PasswordChangedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SecurityVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("passwordHash")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("PasswordHash");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.HasIndex("NormalizedLoginEmail")
                        .IsUnique();

                    b.ToTable("AuthenticationAccounts", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_AuthenticationAccounts_PasswordHashStatus", "([Status] = N'PendingSetup' AND [PasswordHash] IS NULL AND [EmailVerifiedUtc] IS NULL AND [PasswordChangedUtc] IS NULL) OR ([Status] IN (N'Active', N'Disabled') AND [PasswordHash] IS NOT NULL AND [EmailVerifiedUtc] IS NOT NULL AND [PasswordChangedUtc] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Identities.Identity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdentityId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("Id");

                    b.HasIndex("Subject")
                        .IsUnique();

                    b.ToTable("Identities", "platform");
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Roles.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RoleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedRoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedRoleName")
                        .IsUnique();

                    b.ToTable("Roles", "platform");
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Roles.RolePermissionAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AssignmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("AssignedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("RemovedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("RemovedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RoleId", "PermissionName")
                        .IsUnique()
                        .HasFilter("[RemovedUtc] IS NULL");

                    b.ToTable("RolePermissionAssignments", "platform");
                });

            modelBuilder.Entity("SSAS.Platform.Domain.TenantUsers.TenantUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TenantUserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<long>("IdentityId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.HasIndex("TenantId", "IdentityId")
                        .IsUnique();

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique();

                    b.ToTable("TenantUsers", "platform");
                });

            modelBuilder.Entity("SSAS.Platform.Domain.TenantUsers.TenantUserRoleAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AssignmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("AssignedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RemovedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("RemovedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TenantUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RoleId");

                    b.HasIndex("TenantId", "TenantUserId", "RoleId")
                        .IsUnique()
                        .HasFilter("[RemovedUtc] IS NULL");

                    b.ToTable("TenantUserRoleAssignments", "platform");
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Authentication.AccountActionToken", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Authentication.AuthenticationAccount", null)
                        .WithMany()
                        .HasForeignKey("AuthenticationAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.Platform.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.Platform.Domain.TenantUsers.TenantUser", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TenantUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Authentication.AuthenticationAccount", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Identities.Identity", null)
                        .WithOne()
                        .HasForeignKey("SSAS.Platform.Domain.Authentication.AuthenticationAccount", "IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Roles.RolePermissionAssignment", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Roles.Role", null)
                        .WithMany("PermissionAssignments")
                        .HasForeignKey("TenantId", "RoleId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.Platform.Domain.TenantUsers.TenantUser", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.Platform.Domain.TenantUsers.TenantUserRoleAssignment", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RoleId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.Platform.Domain.TenantUsers.TenantUser", null)
                        .WithMany("RoleAssignments")
                        .HasForeignKey("TenantId", "TenantUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Roles.Role", b =>
                {
                    b.Navigation("PermissionAssignments");
                });

            modelBuilder.Entity("SSAS.Platform.Domain.TenantUsers.TenantUser", b =>
                {
                    b.Navigation("RoleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
