// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSAS.Platform.Infrastructure.Persistence;

#nullable disable

namespace SSAS.Platform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260801135811_AddUserLogoutSessionRevocationReason")]
    partial class AddUserLogoutSessionRevocationReason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SSAS.Platform.Domain.Authentication.AccountActionToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AccountActionTokenId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthenticationAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ConsumedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("IdentityId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("IssuedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("RevokedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("TenantUserId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("secretHash")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("SecretHash")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("AuthenticationAccountId");

                    b.HasIndex("IdentityId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("secretHash")
                        .IsUnique();

                    b.HasIndex("Purpose", "AuthenticationAccountId")
                        .IsUnique()
                        .HasFilter("[ConsumedUtc] IS NULL AND [RevokedUtc] IS NULL AND [TenantUserId] IS NULL");

                    b.HasIndex("TenantId", "TenantUserId");

                    b.HasIndex("Purpose", "TenantId", "TenantUserId")
                        .IsUnique()
                        .HasFilter("[ConsumedUtc] IS NULL AND [RevokedUtc] IS NULL AND [TenantUserId] IS NOT NULL");

                    b.ToTable("AccountActionTokens", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_AccountActionTokens_Expiry", "[ExpiresUtc] > [IssuedUtc]");

                            t.HasCheckConstraint("CK_AccountActionTokens_OwnershipBinding", "([Purpose] = N'Invitation' AND [TenantId] IS NOT NULL AND [TenantUserId] IS NOT NULL) OR ([Purpose] = N'PasswordReset' AND [TenantId] IS NULL AND [TenantUserId] IS NULL)");
                        });
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Authentication.AuthenticationAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AuthenticationAccountId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EmailVerifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("int");

                    b.Property<long>("IdentityId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LockoutEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LoginEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedLoginEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset?>("PasswordChangedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SecurityVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("passwordHash")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("PasswordHash");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.HasIndex("NormalizedLoginEmail")
                        .IsUnique();

                    b.ToTable("AuthenticationAccounts", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_AuthenticationAccounts_PasswordHashStatus", "([Status] = N'PendingSetup' AND [PasswordHash] IS NULL AND [EmailVerifiedUtc] IS NULL AND [PasswordChangedUtc] IS NULL) OR ([Status] IN (N'Active', N'Disabled') AND [PasswordHash] IS NOT NULL AND [EmailVerifiedUtc] IS NOT NULL AND [PasswordChangedUtc] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Authentication.AuthenticationSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AuthenticationSessionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AbsoluteExpiresUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long?>("CompromisedByRefreshTokenRecordId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CompromisedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("IdentityId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("IdleExpiresUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastRefreshedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("RevokedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SecurityVersionAtCreation")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TenantUserId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TokenFamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "TokenFamilyId", "ClientId")
                        .HasName("AK_AuthenticationSessions_SessionFamilyClient");

                    b.HasIndex("IdentityId", "CreatedUtc", "Id")
                        .HasDatabaseName("IX_AuthenticationSessions_Identity_Created");

                    b.HasIndex("TenantId", "TenantUserId", "IdentityId")
                        .HasDatabaseName("IX_AuthenticationSessions_TenantMembershipIdentity");

                    b.HasIndex("IdentityId", "Status", "IdleExpiresUtc", "AbsoluteExpiresUtc")
                        .HasDatabaseName("IX_AuthenticationSessions_Identity_ActiveExpiry");

                    b.ToTable("AuthenticationSessions", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_AuthenticationSessions_Expiry", "[IdleExpiresUtc] > [CreatedUtc] AND [AbsoluteExpiresUtc] > [CreatedUtc] AND [IdleExpiresUtc] <= [AbsoluteExpiresUtc]");

                            t.HasCheckConstraint("CK_AuthenticationSessions_LifecycleMetadata", "([Status] = N'Active' AND [RevokedUtc] IS NULL AND [RevocationReason] IS NULL AND [CompromisedUtc] IS NULL AND [CompromisedByRefreshTokenRecordId] IS NULL) OR ([Status] = N'Revoked' AND [RevokedUtc] IS NOT NULL AND [RevocationReason] IS NOT NULL AND [CompromisedUtc] IS NULL AND [CompromisedByRefreshTokenRecordId] IS NULL) OR ([Status] = N'Compromised' AND [RevokedUtc] IS NULL AND [RevocationReason] IS NULL AND [CompromisedUtc] IS NOT NULL AND [CompromisedByRefreshTokenRecordId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_AuthenticationSessions_RevocationReason", "[RevocationReason] IS NULL OR [RevocationReason] IN (N'SessionLimitExceeded', N'PasswordReset', N'SecurityStateChanged', N'IdentityIneligible', N'MembershipIneligible', N'TenantIneligible', N'Administrative', N'UserLogout')");

                            t.HasCheckConstraint("CK_AuthenticationSessions_Status", "[Status] IN (N'Active', N'Revoked', N'Compromised')");
                        });
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Authentication.RefreshTokenRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RefreshTokenRecordId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthenticationSessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset?>("ConsumedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("ReplacedByRefreshTokenRecordId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("RevokedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TokenFamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("secretHash")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("SecretHash")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasAlternateKey("AuthenticationSessionId", "TokenFamilyId", "ClientId", "Id")
                        .HasName("AK_RefreshTokenRecords_SessionFamilyClientRecord");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("UX_RefreshTokenRecords_PublicId");

                    b.HasIndex("ReplacedByRefreshTokenRecordId")
                        .IsUnique()
                        .HasDatabaseName("UX_RefreshTokenRecords_Replacement")
                        .HasFilter("[ReplacedByRefreshTokenRecordId] IS NOT NULL");

                    b.HasIndex("AuthenticationSessionId", "CreatedUtc")
                        .HasDatabaseName("IX_RefreshTokenRecords_Session_Created");

                    b.HasIndex("AuthenticationSessionId", "TokenFamilyId", "ClientId", "ReplacedByRefreshTokenRecordId");

                    b.ToTable("RefreshTokenRecords", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_RefreshTokenRecords_Expiry", "[ExpiresUtc] > [CreatedUtc]");

                            t.HasCheckConstraint("CK_RefreshTokenRecords_Lifecycle", "NOT ([ConsumedUtc] IS NOT NULL AND [RevokedUtc] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Authentication.TenantSelectionTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TenantSelectionTransactionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset?>("ConsumedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("IdentityId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RevokedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SecurityVersionAtAuthentication")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("secretHash")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("SecretHash")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("UX_TenantSelectionTransactions_PublicId");

                    b.HasIndex("ConsumedUtc", "RevokedUtc", "ExpiresUtc")
                        .HasDatabaseName("IX_TenantSelectionTransactions_Unresolved");

                    b.HasIndex("IdentityId", "ClientId", "ConsumedUtc", "RevokedUtc", "ExpiresUtc")
                        .HasDatabaseName("IX_TenantSelectionTransactions_IdentityClientLifecycle");

                    b.ToTable("TenantSelectionTransactions", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_TenantSelectionTransactions_Expiry", "[ExpiresUtc] > [CreatedUtc]");

                            t.HasCheckConstraint("CK_TenantSelectionTransactions_Lifecycle", "NOT ([ConsumedUtc] IS NOT NULL AND [RevokedUtc] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Identities.Identity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdentityId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("Id");

                    b.HasIndex("Subject")
                        .IsUnique();

                    b.ToTable("Identities", "platform");
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Roles.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RoleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedRoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedRoleName")
                        .IsUnique();

                    b.ToTable("Roles", "platform");
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Roles.RolePermissionAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AssignmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("AssignedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("RemovedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("RemovedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RoleId", "PermissionName")
                        .IsUnique()
                        .HasFilter("[RemovedUtc] IS NULL");

                    b.ToTable("RolePermissionAssignments", "platform");
                });

            modelBuilder.Entity("SSAS.Platform.Domain.TenantUsers.TenantUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TenantUserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<long>("IdentityId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.HasIndex("TenantId", "IdentityId")
                        .IsUnique();

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique();

                    b.ToTable("TenantUsers", "platform");
                });

            modelBuilder.Entity("SSAS.Platform.Domain.TenantUsers.TenantUserRoleAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AssignmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("AssignedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RemovedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("RemovedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TenantUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RoleId");

                    b.HasIndex("TenantId", "TenantUserId", "RoleId")
                        .IsUnique()
                        .HasFilter("[RemovedUtc] IS NULL");

                    b.ToTable("TenantUserRoleAssignments", "platform");
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedTenantCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StatusChangeReasonCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StatusChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("StatusChangedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TenantCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedTenantCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Tenants_NormalizedTenantCode");

                    b.HasIndex("Status", "TenantName", "Id")
                        .HasDatabaseName("IX_Tenants_Status_TenantName_TenantId");

                    b.ToTable("Tenants", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_Tenants_Status", "[Status] IN (N'Provisioning', N'Active', N'Suspended', N'Archived')");

                            t.HasCheckConstraint("CK_Tenants_StatusChangeReasonCode", "[StatusChangeReasonCode] IN (N'Created', N'ProvisioningCompleted', N'Administrative', N'Security', N'Compliance', N'Operational', N'CustomerClosure', N'IssueResolved')");

                            t.HasCheckConstraint("CK_Tenants_StatusMetadata", "[StatusChangedUtc] >= [CreatedUtc]");

                            t.HasCheckConstraint("CK_Tenants_TenantCode_NotBlank", "LEN(LTRIM(RTRIM([TenantCode]))) > 0");

                            t.HasCheckConstraint("CK_Tenants_TenantName_NotBlank", "LEN(LTRIM(RTRIM([TenantName]))) > 0");
                        });
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Authentication.AccountActionToken", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Authentication.AuthenticationAccount", null)
                        .WithMany()
                        .HasForeignKey("AuthenticationAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.Platform.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.Platform.Domain.TenantUsers.TenantUser", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TenantUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Authentication.AuthenticationAccount", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Identities.Identity", null)
                        .WithOne()
                        .HasForeignKey("SSAS.Platform.Domain.Authentication.AuthenticationAccount", "IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Authentication.AuthenticationSession", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.Platform.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.Platform.Domain.TenantUsers.TenantUser", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TenantUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Authentication.RefreshTokenRecord", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Authentication.AuthenticationSession", null)
                        .WithMany("RefreshTokenRecords")
                        .HasForeignKey("AuthenticationSessionId", "TokenFamilyId", "ClientId")
                        .HasPrincipalKey("Id", "TokenFamilyId", "ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.Platform.Domain.Authentication.RefreshTokenRecord", "ReplacedByRefreshTokenRecord")
                        .WithMany()
                        .HasForeignKey("AuthenticationSessionId", "TokenFamilyId", "ClientId", "ReplacedByRefreshTokenRecordId")
                        .HasPrincipalKey("AuthenticationSessionId", "TokenFamilyId", "ClientId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReplacedByRefreshTokenRecord");
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Authentication.TenantSelectionTransaction", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Roles.RolePermissionAssignment", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Roles.Role", null)
                        .WithMany("PermissionAssignments")
                        .HasForeignKey("TenantId", "RoleId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.Platform.Domain.TenantUsers.TenantUser", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.Platform.Domain.TenantUsers.TenantUserRoleAssignment", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RoleId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.Platform.Domain.TenantUsers.TenantUser", null)
                        .WithMany("RoleAssignments")
                        .HasForeignKey("TenantId", "TenantUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Authentication.AuthenticationSession", b =>
                {
                    b.Navigation("RefreshTokenRecords");
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Roles.Role", b =>
                {
                    b.Navigation("PermissionAssignments");
                });

            modelBuilder.Entity("SSAS.Platform.Domain.TenantUsers.TenantUser", b =>
                {
                    b.Navigation("RoleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
