using System.Globalization;
using System.Text;

namespace SSAS.Platform.Infrastructure.TenantStorage;

// SQL Server restore-verification command construction (ADR-022 §17, v1.2).
//
// Its own small unit, for the same reason the backup command text is: the two things most worth proving
// about a restore command — that `WITH REPLACE` never appears, and that every logical file is redirected —
// are exactly the things that get lost inside a longer method.
//
// WHAT IS PARAMETERISED AND WHAT IS NOT, stated once because the distinction is the security model:
//
//   Device path and MOVE targets  -> SqlParameter. Never interpolated.
//   Database name                 -> an IDENTIFIER, so it cannot be a parameter; quoted, and generated by
//                                    this platform from two integers, so it contains no caller text at all.
//   Logical file names            -> come from the SERVER's own FILELISTONLY output, and are string LITERALS
//                                    in a MOVE clause; escaped by doubling quotes.
internal static class SqlServerRestoreCommandText
{
  public const string DeviceParameterName = "@device";

  // RESTORE FILELISTONLY. Always issued BEFORE constructing a restore, because the logical file names it
  // returns are the only trustworthy source for the MOVE clauses — a backup's file layout is a property of
  // the backup, not something the platform may assume (ADR-022 §17).
  public static string FileListOnly() =>
    $"RESTORE FILELISTONLY FROM DISK = {DeviceParameterName}";

  // RESTORE HEADERONLY, used to correlate a device to the backup set it actually contains.
  public static string HeaderOnly() =>
    $"RESTORE HEADERONLY FROM DISK = {DeviceParameterName}";

  // Builds one restore step.
  //
  // `WITH REPLACE` IS ABSENT AND UNREACHABLE. There is no parameter, no overload and no branch that can
  // introduce it (ADR-022 compliance rule 38). `REPLACE` is the clause that turns a mistargeted restore from
  // a failed operation into the destruction of an existing database, and verification never needs it because
  // it always restores into a name this platform has just generated for the purpose. A restore into an
  // existing name is a fail-safe condition, not something to overwrite.
  //
  // `NORECOVERY` for every step except the last: a chain must not be recovered until the final segment has
  // been applied, or the remaining segments become unrestorable (ADR-022 §17 Level C).
  public static string Restore(
    string verificationDatabaseName,
    IReadOnlyList<TenantDatabaseVerificationFilePlacement> placements,
    TenantDatabaseRestoreStep step,
    bool recoverAtEnd)
  {
    ArgumentNullException.ThrowIfNull(placements);

    var quoted = SqlServerBackupCommandText.QuoteIdentifier(verificationDatabaseName);
    var verb = step == TenantDatabaseRestoreStep.Log ? "RESTORE LOG" : "RESTORE DATABASE";

    var command = new StringBuilder();
    command.Append(CultureInfo.InvariantCulture, $"{verb} {quoted} FROM DISK = {DeviceParameterName} WITH ");

    // MOVE for EVERY logical file, on the first data restore. Subsequent differential and log steps apply to
    // the database this created, so they do not restate the layout.
    if (step == TenantDatabaseRestoreStep.Full)
    {
      foreach (var placement in placements)
      {
        command.Append(CultureInfo.InvariantCulture,
          $"MOVE {QuoteLiteral(placement.LogicalName)} TO {ParameterFor(placement)}, ");
      }
    }

    // CHECKSUM verifies the set on the way in, which is the same protection the managed backup wrote it
    // with. STATS is deliberately absent: progress noise on a long restore serves nobody here.
    command.Append("CHECKSUM, ");
    command.Append(recoverAtEnd ? "RECOVERY" : "NORECOVERY");

    return command.ToString();
  }

  // The parameter name carrying one MOVE target. Derived from the file's ORDINAL POSITION, never from its
  // logical name: the name comes from the backup and may contain anything, while the position is a small
  // integer this platform assigned.
  public static string ParameterFor(TenantDatabaseVerificationFilePlacement placement)
  {
    ArgumentNullException.ThrowIfNull(placement);
    return ParameterForIndex(placement.Index);
  }

  public static string ParameterForIndex(int index)
  {
    ArgumentOutOfRangeException.ThrowIfNegative(index);
    return string.Create(CultureInfo.InvariantCulture, $"@move{index}");
  }

  // A SQL string literal. Doubling single quotes is the whole escape rule for one, and it is applied because
  // logical file names come from the backup rather than from this platform — the one input in this command
  // that neither configuration nor generation controls.
  public static string QuoteLiteral(string value)
  {
    ArgumentNullException.ThrowIfNull(value);
    return $"N'{value.Replace("'", "''", StringComparison.Ordinal)}'";
  }
}

// Which segment of the chain a restore step applies.
internal enum TenantDatabaseRestoreStep
{
  Full = 1,

  Differential = 2,

  Log = 3
}
