using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using SSAS.BuildingBlocks.Domain;
using SSAS.Platform.Domain.TenantStorage;

namespace SSAS.Platform.Infrastructure.TenantStorage;

// WHAT A TENANT'S DATA ACTUALLY IS, DERIVED FROM THE MODEL (ADR-020, TS-Storage Phase E3).
//
// THE MANIFEST IS NOT A HAND-WRITTEN LIST. It is computed from TenantDbContext's own model, because a
// hard-coded table list is wrong the moment someone adds an entity — and it is wrong SILENTLY, producing a
// copy that validates perfectly against the tables it knows about while leaving a table behind. Deriving it
// means a new tenant-owned entity is covered by construction.
//
// A declared inventory is still asserted separately in the architecture tests. That is not redundancy: the
// derivation guarantees the engine cannot MISS a table, and the declared list guarantees a human SEES a new
// one — a new entity may need ordering, identity or column decisions that "it compiles" does not settle.
//
// ORDERING IS BY FOREIGN KEY, principals before dependents, so inserts never violate referential integrity
// and constraints stay ON throughout. A cycle is REPORTED rather than resolved: disabling constraints to
// make a copy fit is how a copy quietly produces a database the application cannot trust.
internal static class TenantCutoverCopyPlan
{
  public static Result<IReadOnlyList<TenantCutoverTablePlan>> Build(IModel model)
  {
    ArgumentNullException.ThrowIfNull(model);

    var tenantOwned = model.GetEntityTypes()
      .Where(entity => !entity.IsOwned())
      .Where(entity => entity.ClrType is not null &&
        typeof(ITenantOwnedEntity).IsAssignableFrom(entity.ClrType))
      .Where(entity => entity.GetTableName() is not null)
      .ToArray();

    var plans = new Dictionary<IEntityType, TenantCutoverTablePlan>();
    foreach (var entity in tenantOwned)
    {
      var plan = Describe(entity);
      if (plan.IsFailure)
      {
        return Result.Failure<IReadOnlyList<TenantCutoverTablePlan>>(plan.Error);
      }

      plans[entity] = plan.Value;
    }

    return Order(tenantOwned, plans);
  }

  private static Result<TenantCutoverTablePlan> Describe(IEntityType entity)
  {
    var tableName = entity.GetTableName()!;
    var schema = entity.GetSchema() ?? "dbo";
    var store = StoreObjectIdentifier.Table(tableName, entity.GetSchema());

    var columns = new List<string>();
    var identityColumns = new List<string>();

    foreach (var property in entity.GetProperties())
    {
      var column = property.GetColumnName(store);
      if (column is null)
      {
        continue;
      }

      // ROWVERSION IS NEVER COPIED. It is the target's own concurrency state, generated by the target on
      // insert; carrying the source's bytes across would hand the new database a token describing a
      // different database's history. Identified by shape rather than by name so a differently-named
      // rowversion column cannot slip through.
      if (IsRowVersion(property))
      {
        continue;
      }

      // Computed columns are produced by the target from the values that ARE copied. Writing them would
      // fail; recomputing them is the correct semantics.
      if (property.GetComputedColumnSql() is not null)
      {
        continue;
      }

      columns.Add(column);

      // An identity primary key must arrive with the SAME value or every foreign key referencing it breaks.
      // SqlBulkCopy can preserve it, but only if the plan says the column is one.
      if (property.GetValueGenerationStrategy(store) ==
        Microsoft.EntityFrameworkCore.Metadata.SqlServerValueGenerationStrategy.IdentityColumn)
      {
        identityColumns.Add(column);
      }
    }

    var key = entity.FindPrimaryKey();
    if (key is null || columns.Count == 0)
    {
      // Exact validation is defined as an ordered walk over the primary key; without one there is no
      // deterministic order and therefore no exact comparison to make.
      return Result.Failure<TenantCutoverTablePlan>(TenantStorageErrors.CutoverCopyOrderUndecidable);
    }

    var keyColumns = key.Properties
      .Select(property => property.GetColumnName(store))
      .Where(column => column is not null)
      .Select(column => column!)
      .ToArray();

    var tenantColumn = entity.FindProperty(nameof(ITenantOwnedEntity.TenantId))?.GetColumnName(store);
    if (tenantColumn is null)
    {
      return Result.Failure<TenantCutoverTablePlan>(TenantStorageErrors.CutoverCopyOrderUndecidable);
    }

    return Result.Success(new TenantCutoverTablePlan(
      entity.ClrType.Name, schema, tableName, columns, keyColumns, tenantColumn, identityColumns));
  }

  // ROWVERSION, BY SHAPE: a store-generated concurrency token. That is exactly what
  // `.IsRowVersion().IsConcurrencyToken()` produces, and nothing else in this model has that shape.
  private static bool IsRowVersion(IProperty property) =>
    property.IsConcurrencyToken && property.ValueGenerated == ValueGenerated.OnAddOrUpdate;

  // Principals before dependents (Kahn). Self-references are ignored for ordering — a row referencing its
  // own table is satisfied within the single batch its table is copied in — and any remaining cycle across
  // two or more tables is refused rather than worked around.
  private static Result<IReadOnlyList<TenantCutoverTablePlan>> Order(
    IReadOnlyCollection<IEntityType> entities,
    Dictionary<IEntityType, TenantCutoverTablePlan> plans)
  {
    var dependencies = entities.ToDictionary(
      entity => entity,
      entity => entity.GetForeignKeys()
        .Select(foreignKey => foreignKey.PrincipalEntityType)
        .Where(principal => principal != entity && plans.ContainsKey(principal))
        .Distinct()
        .ToHashSet());

    var ordered = new List<TenantCutoverTablePlan>(entities.Count);
    var remaining = new HashSet<IEntityType>(entities);

    while (remaining.Count > 0)
    {
      // Deterministic tie-breaking by table name: the same model must always produce the same copy order,
      // or two instances resuming the same cutover would disagree about which table came next.
      var ready = remaining
        .Where(entity => dependencies[entity].All(principal => !remaining.Contains(principal)))
        .OrderBy(entity => plans[entity].TableName, StringComparer.Ordinal)
        .ToArray();

      if (ready.Length == 0)
      {
        return Result.Failure<IReadOnlyList<TenantCutoverTablePlan>>(
          TenantStorageErrors.CutoverCopyOrderUndecidable);
      }

      foreach (var entity in ready)
      {
        ordered.Add(plans[entity]);
        remaining.Remove(entity);
      }
    }

    return Result.Success<IReadOnlyList<TenantCutoverTablePlan>>(ordered);
  }
}

// One table's copy contract. Everything the copier and the validator need, and nothing that would let
// either of them decide something the model has already decided.
internal sealed record TenantCutoverTablePlan(
  string EntityName,
  string Schema,
  string TableName,
  IReadOnlyList<string> Columns,
  IReadOnlyList<string> PrimaryKeyColumns,
  string TenantIdColumn,
  IReadOnlyList<string> IdentityColumns)
{
  public bool HasIdentityColumn => IdentityColumns.Count > 0;

  public string QualifiedName => $"[{Escape(Schema)}].[{Escape(TableName)}]";

  // The identical projection is used to READ the source and to READ the target back for validation, so a
  // column the copy skipped cannot be a column the validation silently checks, or the reverse.
  public string ColumnList => string.Join(", ", Columns.Select(column => $"[{Escape(column)}]"));

  public string OrderByPrimaryKey =>
    string.Join(", ", PrimaryKeyColumns.Select(column => $"[{Escape(column)}]"));

  // Identifiers come from the EF model rather than from any caller, so this is defence in depth rather than
  // the primary control — but a table name is still never concatenated into SQL unescaped.
  private static string Escape(string identifier) => identifier.Replace("]", "]]", StringComparison.Ordinal);
}
