<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SSAS.HIS.Application\SSAS.HIS.Application.csproj" />
    <ProjectReference Include="..\SSAS.HIS.Contracts\SSAS.HIS.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\SSAS.BuildingBlocks.Api\SSAS.BuildingBlocks.Api.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
