using System;
using SSAS.BuildingBlocks.Domain;

namespace SSAS.HIS.Domain.Entities.InPatient
{
    public class MedicalObservation : ITenantOwnedEntity
    {
        public int Id { get; set; }
        public int PatientID { get; set; }
        public string PateintType { get; set; }
        public string MedicalObservationStatus { get; set; }
        public string IP_OP { get; set; }
        public int DoctorID { get; set; }
        public string MedicalObservationNO { get; set; }
        public string Complaints { get; set; }
        public string HistoryOFPresentIllness { get; set; }
        public string HospitalizationHistory { get; set; }
        public bool IsInsignificant_HospitalizationHistory { get; set; }
        public bool IsInsignificant_PastMedicalHistoryDiseases { get; set; }
        public bool IsInsignificant_PastMedicalHistorySpecialConsiderations { get; set; }
        public bool IsInsignificant_FamilyHistoryDiseases { get; set; }
        public bool IsInsignificant_FamilyHistorySpecialConsiderations { get; set; }
        public bool IsInsignificant_FamilyHistoryPersonalHistory { get; set; }
        public bool IsInsignificant_DrugReactions { get; set; }
        public bool IsInsignificant_CurrMedicationHistory { get; set; }
        public string FamilyHistoryNotes { get; set; }
        public string Remarks { get; set; }
        public string Pulse { get; set; }
        public bool IsRegularPulse { get; set; }
        public string BP { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string TempF { get; set; }
        public string TempC { get; set; }
        public string BMI { get; set; }
        public string SpO2 { get; set; }
        public string GCS { get; set; }
        public string toothNo { get; set; }
        public bool IsInsignificant_NAD { get; set; }
        public bool IsInsignificant_SystemReview { get; set; }
        public string SystemReview { get; set; }
        public bool IsInsignificant_LocalExamination { get; set; }
        public string LocalExamination { get; set; }
        public bool IsInsignificant_Functional { get; set; }
        public bool IsInsignificant_Nutritional { get; set; }
        public bool IsInsignificant_Psychological { get; set; }
        public bool IsInsignificant_SocioEconomic { get; set; }
        public bool IsInsignificant_PainScore { get; set; }
        public bool IsPainManagementDone { get; set; }
        public bool IsInsignificant_AdditionalAssessmente { get; set; }
        public string AdditionalAssessmente { get; set; }
        public string ExpectedLengthOfStay { get; set; }
        public string ExpectedLengthOfStayUnit { get; set; }
        public string MainLinesOfTreatment { get; set; }
        public string MeasurableGoalOfImprovement { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public DateTime LastModifiedDate { get; set; }
        public int CompanyID { get; set; }
        public int SpecialityID { get; set; }
        public bool IsPregnant { get; set; }
        public bool IsLactation { get; set; }
        public int OperationID { get; set; }
        public int AnesthesiaDoctorId { get; set; }
        public int OperationSetupMasterId { get; set; }
        public bool IsOperation { get; set; }
        public string ActionTaken { get; set; }
        public int ActionTakenDoctorID { get; set; }
        public string contor { get; set; }
        public string dilated { get; set; }
        public string hernial { get; set; }
        public string LiverPalp { get; set; }
        public string LiverRtLobe { get; set; }
        public string speen { get; set; }
        public string spleenLTLobe { get; set; }
        public string SpleenLTLobeComment { get; set; }
        public string liverRTLobeComment { get; set; }
        public string RTKidney { get; set; }
        public string RTKidneyComment { get; set; }
        public string LTKidney { get; set; }
        public string LTKidneyComment { get; set; }
        public string colon { get; set; }
        public string colonComment { get; set; }
        public string Ascitls { get; set; }
        public string AscitlsLevel { get; set; }
        public string AscitlsComment { get; set; }
        public string Intestlsound { get; set; }
        public string lepaticrub { get; set; }
        public string splenizrub { get; set; }
        public string LiverLTLobe { get; set; }
        public string allert { get; set; }
        public string Oriented { get; set; }
        public string Memory { get; set; }
        public string Conscious { get; set; }
        public string LNPathy { get; set; }
        public string FlappiesTremor { get; set; }
        public string clubbing { get; set; }
        public string cynofis { get; set; }
        public string jaurdice { get; set; }
        public string pallor { get; set; }
        public string Complaints_Psycho { get; set; }
        public string PrenatalHistory_MaternalInfection { get; set; }
        public string PrenatalHistory_ExposureToRadiation { get; set; }
        public string PrenatalHistory_Other { get; set; }
        public string PrenatalHistory_OtherComment { get; set; }
        public string NatalHistory_TypesofDelivery { get; set; }
        public string NatalHistory_Complications { get; set; }
        public string NatalHistory_ComplicationsComment { get; set; }
        public string NatalHistory_BirthTruma { get; set; }
        public string NatalHistory_BirthTrumaComment { get; set; }
        public string NatalHistory_Milestones { get; set; }
        public string NatalHistory_MilestonesComment { get; set; }
        public string NatalHistory_Language { get; set; }
        public string NatalHistory_Behaviorchildhood_Temper { get; set; }
        public string NatalHistory_Behaviorchildhood_FeedingHabits { get; set; }
        public string NatalHistory_Behaviorchildhood_Pica { get; set; }
        public string NatalHistory_Behaviorchildhood_Tics { get; set; }
        public string NatalHistory_illnesschildhood_CNS { get; set; }
        public string NatalHistory_illnesschildhood_Infection { get; set; }
        public string NatalHistory_illnesschildhood_Epilepsy { get; set; }
        public string NatalHistory_illnesschildhood_NE { get; set; }
        public string NatalHistory_illnesschildhood_Encoporesis { get; set; }
        public string NatalHistory_illnesschildhood_Separationanxiety { get; set; }
        public string NatalHistory_illnesschildhood_Neuroticdisorders { get; set; }
        public string NatalHistory_illnesschildhood_EatingProblems { get; set; }
        public string NatalHistory_Comment { get; set; }
        public string NatalHistory_Education { get; set; }
        public string NatalHistory_Adolescence { get; set; }
        public string NatalHistory_OccupationalHistory { get; set; }
        public string NatalHistory_SexualHistory { get; set; }
        public string NatalHistory_MilitaryHistory { get; set; }
        public string NatalHistory_MaritalHistory { get; set; }
        public string Treatment_Hospitalization { get; set; }
        public string Treatment_Psychopharmacology { get; set; }
        public string Treatment_Psychopharmacology_Comment { get; set; }
        public string Treatment_Psychotheropy { get; set; }
        public string Treatment_Psychotheropy_Comment { get; set; }
        public string Treatment_ECT { get; set; }
        public string Treatment_ECT_Comment { get; set; }
        public string Treatment_TMS { get; set; }
        public string Treatment_TMS_Commrnt { get; set; }
        public string MentalStatus_Appearance_Cooperative { get; set; }
        public string MentalStatus_Appearance_Seductive { get; set; }
        public string MentalStatus_Appearance_Defensive { get; set; }
        public string MentalStatus_Appearance_Hostile { get; set; }
        public string MentalStatus_Appearance_Guarded { get; set; }
        public string MentalStatus_Appearance_Gait { get; set; }
        public string MentalStatus_Appearance_Mannerism { get; set; }
        public string MentalStatus_Appearance_Tics { get; set; }
        public string MentalStatus_Appearance_Retard { get; set; }
        public string MentalStatus_Appearance_Hyperactive { get; set; }
        public string MentalStatus_Appearance_Agitated { get; set; }
        public string MentalStatus_Appearance_Posture { get; set; }
        public string MentalStatus_Appearance_Grooming { get; set; }
        public string MentalStatus_Appearance_Healthy { get; set; }
        public string MentalStatus_Appearance_Frightenend { get; set; }
        public string MentalStatus_Appearance_Anxicty { get; set; }
        public string MentalStatus_Appearance_older { get; set; }
        public string MentalStatus_Appearance_Younger { get; set; }
        public string MentalStatus_Appearance_PooreyeContact { get; set; }
        public string MentalStatus_Appearance_FaireyeContact { get; set; }
        public string MentalStatus_Appearance_NeglectHyg { get; set; }
        public string MentalStatus_Appearance__FairHyg { get; set; }
        public string MentalStatus_Appearance__Comment { get; set; }
        public int MentalStatus_Speech_Rapid { get; set; }
        public string MentalStatus_Speech_Slow { get; set; }
        public string MentalStatus_Speech_Pressured { get; set; }
        public string MentalStatus_Speech_Hesitant { get; set; }
        public string MentalStatus_Speech_Monotonous { get; set; }
        public string MentalStatus_Speech_Loud { get; set; }
        public string MentalStatus_Speech_Whispered { get; set; }
        public string MentalStatus_Speech_Mumbled { get; set; }
        public string MentalStatus_Speech_Comment { get; set; }
        public string MentalStatus_Mood_Depressed { get; set; }
        public string MentalStatus_Mood_anxious { get; set; }
        public string MentalStatus_Mood_angry { get; set; }
        public string MentalStatus_Mood_guilty { get; set; }
        public string MentalStatus_Mood_anhedonia { get; set; }
        public string MentalStatus_Mood_alexithymic { get; set; }
        public string MentalStatus_Mood_Comment { get; set; }
        public string MentalStatus_Affect_Restricted { get; set; }
        public string MentalStatus_Affect_Blunted { get; set; }
        public string MentalStatus_Affect_Flat { get; set; }
        public string MentalStatus_Affect_Comment { get; set; }
        public string MentalStatus_Thinking_a_paucity { get; set; }
        public string MentalStatus_Thinking_a_flight { get; set; }
        public int MentalStatus_Thinking_a_Rapid { get; set; }
        public string MentalStatus_Thinking_a_Slow { get; set; }
        public string MentalStatus_Thinking_a_taneouslt { get; set; }
        public string MentalStatus_Thinking_a_Question { get; set; }
        public string MentalStatus_Thinking_a_Directed { get; set; }
        public string MentalStatus_Thinking_a_Tangentaial { get; set; }
        public string MentalStatus_Thinking_a_Circumstantial { get; set; }
        public string MentalStatus_Thinking_b_Delusion { get; set; }
        public string MentalStatus_Thinking_b_Obsession { get; set; }
        public string MentalStatus_Thinking_b_Compulsion { get; set; }
        public string MentalStatus_Thinking_b_Phobias { get; set; }
        public string MentalStatus_Thinking_b_Suicide { get; set; }
        public string MentalStatus_Thinking_b_Homicide { get; set; }
        public string MentalStatus_Thinking_b_Comments { get; set; }
        public string MentalStatus_Thinking_a_Comments { get; set; }
        public string MentalStatus_Thinking_a_Block { get; set; }
        public string MentalStatus_Thinking_a_distractable { get; set; }
        public string MentalStatus_Thinking_a_Loose { get; set; }
        public string MentalStatus_Thinking_a_incohorent { get; set; }
        public string MentalStatus_Thinking_a_wordsalad { get; set; }
        public string MentalStatus_Thinking_a_neologism { get; set; }
        public string MentalStatus_Thinking_c_reading { get; set; }
        public string MentalStatus_Thinking_c_insertion { get; set; }
        public string MentalStatus_Thinking_c_withdrawal { get; set; }
        public string MentalStatus_Thinking_c_casting { get; set; }
        public string MentalStatus_Thinking_c_Comment { get; set; }
        public string Perception_Comment { get; set; }
        public string Perception_Illusion { get; set; }
        public string Perception_Depersonalization { get; set; }
        public string Perception_Derealization { get; set; }
        public string Perception_Hallucination { get; set; }
        public string Sensorium_a_Conscious { get; set; }
        public string Sensorium_a_Fluctuation { get; set; }
        public string Sensorium_a_Stupor { get; set; }
        public string Sensorium_a_Lethargy { get; set; }
        public string Sensorium_a_FugueState { get; set; }
        public string Sensorium_a_Coma { get; set; }
        public string Sensorium_a_Comment { get; set; }
        public DateTime Sensorium_b_Time { get; set; }
        public string Sensorium_b_place { get; set; }
        public string Sensorium_b_Person { get; set; }
        public string Sensorium_b_Comment { get; set; }
        public string Sensorium_c_Comment { get; set; }
        public string Sensorium_c_Subtract { get; set; }
        public string Sensorium_d_RemoteMemory { get; set; }
        public string Sensorium_d_RecentMemory { get; set; }
        public string Sensorium_d_Immediate { get; set; }
        public string Sensorium_d_Comment { get; set; }
        public string Sensorium_e_Similarities { get; set; }
        public string Sensorium_e_Concrete { get; set; }
        public string Sensorium_e_Abstract { get; set; }
        public string Sensorium_e_Comment { get; set; }
        public string Sensorium_f_Completedenial { get; set; }
        public string Sensorium_f_partial { get; set; }
        public string Sensorium_f_insight { get; set; }
        public string Sensorium_f_Comment { get; set; }
        public string Sensorium_g_judgment { get; set; }
        public string Sensorium_g_Comment { get; set; }
        public string NatalHistory_Behaviorchildhood_HighTerror { get; set; }
        public string Itching { get; set; }
        public string Itching_Comment { get; set; }
        public string Itching_Location { get; set; }
        public string Itching_Duration { get; set; }
        public string Itching_Freq { get; set; }
        public string Itching_Character { get; set; }
        public string Itching_PainScore { get; set; }
        public string Itching_Radiation { get; set; }
        public string Itching_WhatModifiesPain { get; set; }
        public string Itching_OtherComplains { get; set; }
        public string SimilarCondition1 { get; set; }
        public string PastG6PD { get; set; }
        public string PastAnomaly { get; set; }
        public string PastSickle { get; set; }
        public string FamilyG6PD { get; set; }
        public string FamilyAnomaly { get; set; }
        public string FamilySickle { get; set; }
        public string Family_Historysimilar { get; set; }
        public string PastPeptic { get; set; }
        public string Pastthrombosis { get; set; }
        public string PastPulmonary { get; set; }
        public int PastThyroid { get; set; }
        public string PastTuberculosis { get; set; }
        public string PastHereditary { get; set; }
        public string FamilyCardiacDeath { get; set; }
        public string FamilyCancer { get; set; }
        public string FamilyHereditary { get; set; }
        public string Pulse_Rate { get; set; }
        public string Pulse_regular { get; set; }
        public string Pulse_Rhysim { get; set; }
        public string Pulse_Volume { get; set; }
        public string Pulse_Equelity { get; set; }
        public string Pulse_Charachter { get; set; }
        public string Pulse_PeriphPulses { get; set; }
        public string Pulse_PeripheralPerfusion { get; set; }
        public string Pulse_JVPVolume { get; set; }
        public string Pulse_JVPWave { get; set; }
        public string HernialSite { get; set; }
        public string contourComment { get; set; }
        public string sound1Comment { get; set; }
        public string sound2Comment { get; set; }
        public string sound3Comment { get; set; }
        public bool IsSmoking { get; set; }
        public bool IsSmokingComment { get; set; }
        public bool IsAlcohol { get; set; }
        public bool IsAlcoholComment { get; set; }
        public bool IsDrugs { get; set; }
        public bool IsDrugsComment { get; set; }
        public bool IsDiet { get; set; }
        public bool IsBowels { get; set; }
        public bool IsDietComment { get; set; }
        public bool IsBowelsComment { get; set; }
        public bool IsHandedness { get; set; }
        public string Menstrual_History_Reg { get; set; }
        public string LastMenstrualPeriod { get; set; }
        public string AvarageDuration { get; set; }
        public decimal BleedingAmount { get; set; }
        public string PresentIllness_Onset { get; set; }
        public string PresentIllness_OnsetComment { get; set; }
        public string Course { get; set; }
        public string Duration_Period { get; set; }
        public string Duration_PeriodType { get; set; }
        public string History_Stomatitis { get; set; }
        public string History_StomatitisComment { get; set; }
        public string History_Halitosis { get; set; }
        public string History_HalitosisComment { get; set; }
        public string History_Dyspepsia { get; set; }
        public string History_DyspepsiaComment { get; set; }
        public string History_Dysphagia { get; set; }
        public string History_DysphagiaComment { get; set; }
        public string History_Odynophagia { get; set; }
        public string History_OdynophagiaComment { get; set; }
        public string History_Vomiting { get; set; }
        public string History_VomitingComment { get; set; }
        public string History_Vomiting_Nausea { get; set; }
        public string History_Vomiting_NoAttacks { get; set; }
        public string History_Vomiting_Freq { get; set; }
        public string History_Vomiting_Color { get; set; }
        public string History_Vomiting_Association { get; set; }
        public string History_Diarrhoea { get; set; }
        public string History_DiarrhoeaComment { get; set; }
        public string History_Diarrhoea_Freq { get; set; }
        public string History_Diarrhoea_Color { get; set; }
        public string History_Diarrhoea_Blood { get; set; }
        public string History_Diarrhoea_BloodComment { get; set; }
        public string History_Diarrhoea_Tenesmus { get; set; }
        public string History_Diarrhoea_TenesmusComment { get; set; }
        public string History_Diarrhoea_Association { get; set; }
        public string History_Constipation { get; set; }
        public string History_ConstipationComment { get; set; }
        public string History_Constipation_Freq { get; set; }
        public string History_Constipation_Consistancy { get; set; }
        public string History_Constipation_Dyschezia { get; set; }
        public string History_Constipation_DyscheziaComment { get; set; }
        public string History_Constipation_Flatulence { get; set; }
        public string History_Constipation_FlatulenceComment { get; set; }
        public string History_Constipation_Hema { get; set; }
        public string History_Constipation_HemaComment { get; set; }
        public string History_Abdomina { get; set; }
        public string History_AbdominaComment { get; set; }
        public string History_Abdomina_Site { get; set; }
        public string History_Abdomina_Character { get; set; }
        public string History_Abdomina_increase { get; set; }
        public string History_Abdomina_Decrease { get; set; }
        public string History_Abdomina_Referral { get; set; }
        public string History_Abdomina_Association { get; set; }
        public string History_Haematemesis { get; set; }
        public string History_HaematemesisComment { get; set; }
        public string History_Haematemesis_Color { get; set; }
        public string History_Haematemesis_Freq { get; set; }
        public string History_Haematemesis_Association { get; set; }
        public bool IsContraceptive_Method { get; set; }
        public string Contraceptive_Method { get; set; }
        public string Jaundice_Yellowish { get; set; }
        public string Jaundice_Yellowish_Comment { get; set; }
        public string Jaundice_DarkBrown { get; set; }
        public string Jaundice_DarkBrown_Comment { get; set; }
        public string Jaundice_SoftClay { get; set; }
        public string Jaundice_SoftClay_Comment { get; set; }
        public string Jaundice_itching { get; set; }
        public string Jaundice_itching_Comment { get; set; }
        public string Jaundice_Fever { get; set; }
        public string Jaundice_Fever_Comment { get; set; }
        public string Jaundice_AbdominalPain { get; set; }
        public string Jaundice_AbdominalPain_Comment { get; set; }
        public string BleedingTendency { get; set; }
        public string BleedingTendency_Gums { get; set; }
        public string BleedingTendency_Gums_Comments { get; set; }
        public string BleedingTendency_Epitaxis { get; set; }
        public string BleedingTendency_Epitaxis_Comment { get; set; }
        public string BleedingTendency_Ecchymosis { get; set; }
        public string BleedingTendency_Ecchymosis_Comment { get; set; }
        public string EnlargedAbdomen { get; set; }
        public string EnlargedAbdomen_Site { get; set; }
        public string EnlargedAbdomen_Site_Comment { get; set; }
        public string EnlargedAbdomen_Association { get; set; }
        public string EnlargedAbdomen_Association_Comment { get; set; }
        public string Encephalopathy { get; set; }
        public string Encephalopathy_FlappingTremors { get; set; }
        public string Encephalopathy_FlappingTremors_Comment { get; set; }
        public string Encephalopathy_Rhythm { get; set; }
        public string Encephalopathy_Rhythm_Comment { get; set; }
        public string Encephalopathy_conscious { get; set; }
        public string Encephalopathy_conscious_Comment { get; set; }
        public string Encephalopathy_Admitted { get; set; }
        public string Encephalopathy_Admitted_Comment { get; set; }
        public string Encephalopathy_Precipitating { get; set; }
        public string Encephalopathy_Precipitating_Comment { get; set; }
        public string Toxic { get; set; }
        public string Toxic_Comment { get; set; }
        public string Toxic_Appetit { get; set; }
        public string Toxic_Appetit_Comment { get; set; }
        public string Toxic_weight { get; set; }
        public string Toxic_weight_Comment { get; set; }
        public string Toxic_Fever { get; set; }
        public string Toxic_Fever_Comment { get; set; }
        public string Toxic_Sweat { get; set; }
        public string Toxic_Sweat_Comment { get; set; }
        public string Contour { get; set; }
        public string Contour2 { get; set; }
        public string Umbiticus_Comment { get; set; }
        public string Umbiticus_Site { get; set; }
        public string Umbiticus_Shape { get; set; }
        public string Umbiticus_Secretion { get; set; }
        public string Umbiticus_Vein { get; set; }
        public string Umbiticus_Hernia { get; set; }
        public string DilatedVeins { get; set; }
        public string DilatedVeins_Comment { get; set; }
        public string DilatedVeins_Site { get; set; }
        public string DilatedVeins_Direction { get; set; }
        public string DilatedVeins_Burrowi { get; set; }
        public string Hernia { get; set; }
        public string Hernia_Comment { get; set; }
        public string Hernia2 { get; set; }
        public string DivaricationRecti { get; set; }
        public string DivaricationRecti_Comment { get; set; }
        public string Skin_Hair { get; set; }
        public string Skin_Hair_Comment { get; set; }
        public string Skin_Pigmentation { get; set; }
        public string Skin_Pigmentation_Comment { get; set; }
        public string Skin_Scratch { get; set; }
        public string Skin_Scratch_Comment { get; set; }
        public string Skin_Scar { get; set; }
        public string Skin_Scar_Comment { get; set; }
        public string Skin_Site { get; set; }
        public string Skin_Lenght { get; set; }
        public string Skin_Healing { get; set; }
        public string Skin_Hernia { get; set; }
        public string Epigastrium { get; set; }
        public string Epigastrium_Comment { get; set; }
        public string Epigastrium_Direction { get; set; }
        public string Pedal_Oedema { get; set; }
        public string Pedal_Oedema_Comment { get; set; }
        public string Venous_Hum { get; set; }
        public string RenalArteryStenosis { get; set; }
        public string Venous_HumComment { get; set; }
        public string RenalArteryStenosis_Comment { get; set; }
        public string HepaticRubComment { get; set; }
        public string SplenicRubComment { get; set; }
        public string RTConsistancy { get; set; }
        public string RTEdge { get; set; }
        public string RTPulsation { get; set; }
        public string RTSize { get; set; }
        public string RTSurface { get; set; }
        public string RTTenderness { get; set; }
        public string LTConsistancy { get; set; }
        public string LTEdge { get; set; }
        public string LTPulsation { get; set; }
        public string LTSize { get; set; }
        public string LTSurface { get; set; }
        public string LTTenderness { get; set; }
        public string SpleenConsistancy { get; set; }
        public string SpleenEdge { get; set; }
        public string SpleenPulsation { get; set; }
        public string SpleenSize { get; set; }
        public string SpleenSurface { get; set; }
        public string SpleenTenderness { get; set; }
        public string PastMedicalComment { get; set; }
        public string MissingToothReason { get; set; }
        public string snomedTxt { get; set; }
        public string snomedCode { get; set; }
        public Guid TenantId { get; set; }
    }
}
