// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSAS.Platform.Infrastructure.Persistence.TenantErp;

#nullable disable

namespace SSAS.Platform.Infrastructure.Persistence.TenantErp.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260824175418_AddPayrollFoundation")]
    partial class AddPayrollFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SSAS.GL.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedCode")
                        .IsUnique()
                        .HasDatabaseName("UX_GlAccounts_Tenant_NormalizedCode");

                    b.ToTable("GlAccounts", "tenant");
                });

            modelBuilder.Entity("SSAS.GL.Domain.Calendar.FiscalPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FiscalYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FiscalYearId", "StartUtc")
                        .HasDatabaseName("IX_GlFiscalPeriods_Year_Start");

                    b.ToTable("GlFiscalPeriods", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_GlFiscalPeriods_Range", "[EndUtc] > [StartUtc]");

                            t.HasCheckConstraint("CK_GlFiscalPeriods_Status", "[Status] IN (N'Open', N'Closed')");
                        });
                });

            modelBuilder.Entity("SSAS.GL.Domain.Calendar.FiscalYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TenantId", "CompanyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_GlFiscalYears_Tenant_Company_Code");

                    b.ToTable("GlFiscalYears", "tenant");
                });

            modelBuilder.Entity("SSAS.GL.Domain.Journals.JournalDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("EntryDateUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reference")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_GlJournalDrafts_Tenant_Company");

                    b.ToTable("GlJournalDrafts", "tenant");
                });

            modelBuilder.Entity("SSAS.GL.Domain.Journals.JournalDraftLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Credit")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("Debit")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("JournalDraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("JournalDraftId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_GlJournalDraftLines_Draft_LineNumber");

                    b.ToTable("GlJournalDraftLines", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_GlJournalDraftLines_SingleSided", "([Debit] > 0 AND [Credit] = 0) OR ([Credit] > 0 AND [Debit] = 0)");
                        });
                });

            modelBuilder.Entity("SSAS.GL.Domain.Journals.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("EntryDateUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FiscalPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FiscalYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JournalNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reference")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("ReversesJournalEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ReversesJournalEntryId");

                    b.HasIndex("TenantId", "ReversesJournalEntryId")
                        .IsUnique()
                        .HasDatabaseName("UX_GlJournalEntries_OneReversalPerOriginal")
                        .HasFilter("[ReversesJournalEntryId] IS NOT NULL");

                    b.HasIndex("TenantId", "CompanyId", "EntryDateUtc")
                        .HasDatabaseName("IX_GlJournalEntries_Tenant_Company_EntryDate");

                    b.HasIndex("TenantId", "CompanyId", "FiscalYearId", "JournalNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_GlJournalEntries_Tenant_Company_Year_Number");

                    b.ToTable("GlJournalEntries", "tenant");
                });

            modelBuilder.Entity("SSAS.GL.Domain.Journals.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Credit")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("Debit")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("JournalEntryId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_GlJournalLines_Entry_LineNumber");

                    b.HasIndex("TenantId", "AccountId")
                        .HasDatabaseName("IX_GlJournalLines_Tenant_Account");

                    b.ToTable("GlJournalLines", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_GlJournalLines_SingleSided", "([Debit] > 0 AND [Credit] = 0) OR ([Credit] > 0 AND [Debit] = 0)");
                        });
                });

            modelBuilder.Entity("SSAS.HR.Domain.Departments.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DepartmentId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StatusChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("StatusChangedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ParentDepartmentId");

                    b.HasIndex("TenantId", "CompanyId", "NormalizedCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Departments_TenantId_CompanyId_NormalizedCode");

                    b.HasIndex("TenantId", "CompanyId", "ParentDepartmentId")
                        .HasDatabaseName("IX_Departments_TenantId_CompanyId_ParentDepartmentId");

                    b.ToTable("Departments", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_Departments_Code_NotBlank", "LEN(LTRIM(RTRIM([Code]))) > 0");

                            t.HasCheckConstraint("CK_Departments_Name_NotBlank", "LEN(LTRIM(RTRIM([Name]))) > 0");

                            t.HasCheckConstraint("CK_Departments_ParentIsNotSelf", "[ParentDepartmentId] IS NULL OR [ParentDepartmentId] <> [DepartmentId]");

                            t.HasCheckConstraint("CK_Departments_Status", "[Status] IN (N'Active', N'Inactive')");
                        });
                });

            modelBuilder.Entity("SSAS.HR.Domain.Departments.DepartmentManager", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DepartmentId");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("AssignedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TenantId", "CompanyId", "EmployeeId")
                        .HasDatabaseName("IX_DepartmentManagers_TenantId_CompanyId_EmployeeId");

                    b.ToTable("DepartmentManagers", "tenant");
                });

            modelBuilder.Entity("SSAS.HR.Domain.Departments.EmployeeDepartmentAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeDepartmentAssignmentId");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DestinationDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ReasonText")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("SourceDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DestinationDepartmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SourceDepartmentId");

                    b.HasIndex("TenantId", "CompanyId", "EmployeeId", "EffectiveFromUtc", "Id")
                        .HasDatabaseName("IX_EmployeeDepartmentAssignments_TenantId_CompanyId_EmployeeId_EffectiveFromUtc_Id");

                    b.ToTable("EmployeeDepartmentAssignments", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeDepartmentAssignments_SourceDiffersFromDestination", "[SourceDepartmentId] IS NULL OR [SourceDepartmentId] <> [DestinationDepartmentId]");
                        });
                });

            modelBuilder.Entity("SSAS.HR.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeId");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("EmploymentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NormalizedEmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("NormalizedNationalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StatusChangeReasonCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StatusChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("StatusChangedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("TerminationDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.HasIndex("TenantId", "CompanyId", "DepartmentId")
                        .HasDatabaseName("IX_Employees_TenantId_CompanyId_DepartmentId");

                    b.HasIndex("TenantId", "CompanyId", "NormalizedEmployeeNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Employees_TenantId_CompanyId_NormalizedEmployeeNumber");

                    b.HasIndex("TenantId", "CompanyId", "NormalizedNationalId")
                        .IsUnique()
                        .HasDatabaseName("UX_Employees_TenantId_CompanyId_NormalizedNationalId")
                        .HasFilter("[NormalizedNationalId] IS NOT NULL");

                    b.HasIndex("TenantId", "CompanyId", "PositionId")
                        .HasDatabaseName("IX_Employees_TenantId_CompanyId_PositionId");

                    b.HasIndex("TenantId", "CompanyId", "BranchId", "Status")
                        .HasDatabaseName("IX_Employees_TenantId_CompanyId_BranchId_Status");

                    b.ToTable("Employees", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_Employees_EmployeeNumber_NotBlank", "LEN(LTRIM(RTRIM([EmployeeNumber]))) > 0");

                            t.HasCheckConstraint("CK_Employees_FullName_NotBlank", "LEN(LTRIM(RTRIM([FullName]))) > 0");

                            t.HasCheckConstraint("CK_Employees_Status", "[Status] IN (N'Active', N'Inactive', N'Terminated')");

                            t.HasCheckConstraint("CK_Employees_StatusChangeReasonCode", "[StatusChangeReasonCode] IN (N'Created', N'Administrative', N'Operational', N'Compliance', N'Resignation', N'Dismissal', N'EndOfContract')");

                            t.HasCheckConstraint("CK_Employees_TerminationDateMatchesStatus", "([Status] = N'Terminated' AND [TerminationDate] IS NOT NULL) OR ([Status] <> N'Terminated' AND [TerminationDate] IS NULL)");

                            t.HasCheckConstraint("CK_Employees_TerminationNotBeforeEmployment", "[TerminationDate] IS NULL OR [TerminationDate] >= [EmploymentDate]");
                        });
                });

            modelBuilder.Entity("SSAS.HR.Domain.Employees.EmployeeBranchAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeBranchAssignmentId");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DestinationBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ReasonText")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("SourceBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransferredBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TenantId", "CompanyId", "DestinationBranchId", "EffectiveFromUtc")
                        .HasDatabaseName("IX_EmployeeBranchAssignments_TenantId_CompanyId_DestinationBranchId_EffectiveFromUtc");

                    b.HasIndex("TenantId", "EmployeeId", "EffectiveFromUtc", "Id")
                        .HasDatabaseName("IX_EmployeeBranchAssignments_TenantId_EmployeeId_EffectiveFromUtc_Id");

                    b.ToTable("EmployeeBranchAssignments", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeBranchAssignments_InitialAssignmentHasNoSource", "([SourceBranchId] IS NULL AND [ReasonCode] = N'InitialAssignment') OR ([SourceBranchId] IS NOT NULL AND [ReasonCode] <> N'InitialAssignment')");

                            t.HasCheckConstraint("CK_EmployeeBranchAssignments_ReasonCode", "[ReasonCode] IN (N'InitialAssignment', N'Reorganisation', N'OperationalNeed', N'EmployeeRequest', N'BranchClosure', N'Correction')");

                            t.HasCheckConstraint("CK_EmployeeBranchAssignments_SourceDiffersFromDestination", "[SourceBranchId] IS NULL OR [SourceBranchId] <> [DestinationBranchId]");
                        });
                });

            modelBuilder.Entity("SSAS.HR.Domain.ImportExport.EmployeeExportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ExportRunId");

                    b.Property<string>("ColumnSet")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExecutedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ExecutedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<string>("ScopeBranchIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScopeCompanyIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TenantId", "CompanyId", "ExecutedUtc")
                        .HasDatabaseName("IX_EmployeeExportRuns_TenantId_CompanyId_ExecutedUtc");

                    b.ToTable("EmployeeExportRuns", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeExportRuns_ColumnSet_Present", "LEN([ColumnSet]) > 0");

                            t.HasCheckConstraint("CK_EmployeeExportRuns_RowCount_NonNegative", "[RowCount] >= 0");
                        });
                });

            modelBuilder.Entity("SSAS.HR.Domain.ImportExport.EmployeeImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ImportRunId");

                    b.Property<int>("AcceptedCount")
                        .HasColumnType("int");

                    b.Property<int>("ByteCount")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExecutedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ExecutedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ImportKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NormalizedImportKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("int");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "NormalizedImportKey")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeeImportRuns_Company_Key");

                    b.HasIndex("TenantId", "CompanyId", "ExecutedUtc")
                        .HasDatabaseName("IX_EmployeeImportRuns_TenantId_CompanyId_ExecutedUtc");

                    b.ToTable("EmployeeImportRuns", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeImportRuns_AllOrNothing", "([Outcome] = N'Refused' AND [AcceptedCount] = 0) OR ([Outcome] <> N'Refused' AND [AcceptedCount] = [RowCount])");

                            t.HasCheckConstraint("CK_EmployeeImportRuns_Counts_NonNegative", "[ByteCount] >= 0 AND [RowCount] >= 0 AND [AcceptedCount] >= 0 AND [RejectedCount] >= 0");

                            t.HasCheckConstraint("CK_EmployeeImportRuns_Outcome", "[Outcome] IN (N'Validated', N'Applied', N'Refused')");

                            t.HasCheckConstraint("CK_EmployeeImportRuns_RejectedWithinRowCount", "[RejectedCount] <= [RowCount]");
                        });
                });

            modelBuilder.Entity("SSAS.HR.Domain.Positions.EmployeePositionAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeePositionAssignmentId");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DestinationPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ReasonText")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("SourcePositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DestinationPositionId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SourcePositionId");

                    b.HasIndex("TenantId", "CompanyId", "EmployeeId", "EffectiveFromUtc", "Id")
                        .HasDatabaseName("IX_EmployeePositionAssignments_TenantId_CompanyId_EmployeeId_EffectiveFromUtc_Id");

                    b.ToTable("EmployeePositionAssignments", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_EmployeePositionAssignments_SourceDiffersFromDestination", "[SourcePositionId] IS NULL OR [SourcePositionId] <> [DestinationPositionId]");
                        });
                });

            modelBuilder.Entity("SSAS.HR.Domain.Positions.JobGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("JobGradeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("RankOrder")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SalaryGradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StatusChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("StatusChangedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SalaryGradeId");

                    b.HasIndex("TenantId", "CompanyId", "NormalizedCode")
                        .IsUnique()
                        .HasDatabaseName("UX_JobGrades_TenantId_CompanyId_NormalizedCode");

                    b.HasIndex("TenantId", "CompanyId", "RankOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_JobGrades_TenantId_CompanyId_RankOrder");

                    b.HasIndex("TenantId", "CompanyId", "Status")
                        .HasDatabaseName("IX_JobGrades_TenantId_CompanyId_Status");

                    b.ToTable("JobGrades", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_JobGrades_Code_NotBlank", "LEN(LTRIM(RTRIM([Code]))) > 0");

                            t.HasCheckConstraint("CK_JobGrades_Name_NotBlank", "LEN(LTRIM(RTRIM([Name]))) > 0");

                            t.HasCheckConstraint("CK_JobGrades_RankOrder_Positive", "[RankOrder] > 0");

                            t.HasCheckConstraint("CK_JobGrades_Status", "[Status] IN (N'Active', N'Inactive')");
                        });
                });

            modelBuilder.Entity("SSAS.HR.Domain.Positions.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PositionId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("JobGradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StatusChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("StatusChangedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobGradeId");

                    b.HasIndex("TenantId", "CompanyId", "JobGradeId")
                        .HasDatabaseName("IX_Positions_TenantId_CompanyId_JobGradeId");

                    b.HasIndex("TenantId", "CompanyId", "NormalizedCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Positions_TenantId_CompanyId_NormalizedCode");

                    b.HasIndex("TenantId", "CompanyId", "Status")
                        .HasDatabaseName("IX_Positions_TenantId_CompanyId_Status");

                    b.ToTable("Positions", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_Positions_Code_NotBlank", "LEN(LTRIM(RTRIM([Code]))) > 0");

                            t.HasCheckConstraint("CK_Positions_Status", "[Status] IN (N'Active', N'Inactive')");

                            t.HasCheckConstraint("CK_Positions_Title_NotBlank", "LEN(LTRIM(RTRIM([Title]))) > 0");
                        });
                });

            modelBuilder.Entity("SSAS.HR.Domain.Positions.SalaryGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SalaryGradeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("RankOrder")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StatusChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("StatusChangedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TenantId", "CompanyId", "NormalizedCode")
                        .IsUnique()
                        .HasDatabaseName("UX_SalaryGrades_TenantId_CompanyId_NormalizedCode");

                    b.HasIndex("TenantId", "CompanyId", "RankOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_SalaryGrades_TenantId_CompanyId_RankOrder");

                    b.HasIndex("TenantId", "CompanyId", "Status")
                        .HasDatabaseName("IX_SalaryGrades_TenantId_CompanyId_Status");

                    b.ToTable("SalaryGrades", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_SalaryGrades_Amounts_NonNegative", "[MinimumAmount] IS NULL OR ([MinimumAmount] >= 0 AND [MidpointAmount] >= 0 AND [MaximumAmount] >= 0)");

                            t.HasCheckConstraint("CK_SalaryGrades_Amounts_Ordered", "[MinimumAmount] IS NULL OR ([MinimumAmount] <= [MidpointAmount] AND [MidpointAmount] <= [MaximumAmount])");

                            t.HasCheckConstraint("CK_SalaryGrades_Band_Atomic", "([MinimumAmount] IS NULL AND [MidpointAmount] IS NULL AND [MaximumAmount] IS NULL) OR ([MinimumAmount] IS NOT NULL AND [MidpointAmount] IS NOT NULL AND [MaximumAmount] IS NOT NULL)");

                            t.HasCheckConstraint("CK_SalaryGrades_Code_NotBlank", "LEN(LTRIM(RTRIM([Code]))) > 0");

                            t.HasCheckConstraint("CK_SalaryGrades_Name_NotBlank", "LEN(LTRIM(RTRIM([Name]))) > 0");

                            t.HasCheckConstraint("CK_SalaryGrades_RankOrder_Positive", "[RankOrder] > 0");

                            t.HasCheckConstraint("CK_SalaryGrades_Status", "[Status] IN (N'Active', N'Inactive')");
                        });
                });

            modelBuilder.Entity("SSAS.Payroll.Domain.Compensation.EmployeeCompensation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GradeBandObservation")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WasOutsideGradeBand")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TenantId", "CompanyId", "EmployeeId", "EffectiveFromUtc")
                        .IsDescending(false, false, false, true);

                    b.ToTable("PayrollEmployeeCompensation", "tenant");
                });

            modelBuilder.Entity("SSAS.Payroll.Domain.Compensation.PayElementAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeCompensationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PayElementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("RateOrAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PayElementId");

                    b.HasIndex("EmployeeCompensationId", "PayElementId")
                        .IsUnique();

                    b.ToTable("PayrollElementAssignments", "tenant");
                });

            modelBuilder.Entity("SSAS.Payroll.Domain.Elements.PayElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Behaviour")
                        .HasColumnType("int");

                    b.Property<int>("CalculationOrder")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("DefaultRateOrAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid?>("GlAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TenantId", "CompanyId", "NormalizedCode")
                        .IsUnique();

                    b.ToTable("PayrollElements", "tenant");
                });

            modelBuilder.Entity("SSAS.Payroll.Domain.Runs.PayrollPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FiscalPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("PayDateUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TenantId", "CompanyId", "FiscalPeriodId")
                        .IsUnique();

                    b.ToTable("PayrollPeriods", "tenant");
                });

            modelBuilder.Entity("SSAS.Payroll.Domain.Runs.PayrollRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ApprovedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CalculatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("CalculatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("JournalEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PayrollPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("PostedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PayrollPeriodId");

                    b.HasIndex("TenantId", "CompanyId", "PayrollPeriodId")
                        .IsUnique();

                    b.ToTable("PayrollRuns", "tenant");
                });

            modelBuilder.Entity("SSAS.Payroll.Domain.Runs.PayrollRunDraftLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GlAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid>("PayElementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PayrollRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PayElementId");

                    b.HasIndex("PayrollRunId", "EmployeeId", "Sequence");

                    b.ToTable("PayrollRunDraftLines", "tenant");
                });

            modelBuilder.Entity("SSAS.Payroll.Domain.Runs.PayrollRunLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GlAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid>("PayElementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PayrollRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PayElementId");

                    b.HasIndex("PayrollRunId", "EmployeeId", "Sequence");

                    b.ToTable("PayrollRunLines", "tenant");
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Branches.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BranchId");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMainBranch")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedBranchCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("UX_Branches_TenantId_MainBranch")
                        .HasFilter("[IsMainBranch] = 1 AND [IsActive] = 1");

                    b.HasIndex("TenantId", "NormalizedBranchCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Branches_TenantId_NormalizedBranchCode");

                    b.HasIndex("TenantId", "IsActive", "BranchName")
                        .HasDatabaseName("IX_Branches_TenantId_IsActive_BranchName");

                    b.ToTable("Branches", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_Branches_BranchCode_NotBlank", "LEN(LTRIM(RTRIM([BranchCode]))) > 0");

                            t.HasCheckConstraint("CK_Branches_BranchName_NotBlank", "LEN(LTRIM(RTRIM([BranchName]))) > 0");
                        });
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<string>("BaseCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedCompanyCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StatusChangeReasonCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StatusChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("StatusChangedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedCompanyCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Companies_TenantId_NormalizedCompanyCode");

                    b.HasIndex("TenantId", "Status", "CompanyName", "Id")
                        .HasDatabaseName("IX_Companies_TenantId_Status_CompanyName_CompanyId");

                    b.ToTable("Companies", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_Companies_BaseCurrencyCode", "[BaseCurrencyCode] LIKE '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("CK_Companies_CompanyCode_NotBlank", "LEN(LTRIM(RTRIM([CompanyCode]))) > 0");

                            t.HasCheckConstraint("CK_Companies_CompanyName_NotBlank", "LEN(LTRIM(RTRIM([CompanyName]))) > 0");

                            t.HasCheckConstraint("CK_Companies_Status", "[Status] IN (N'Inactive', N'Active', N'Archived')");

                            t.HasCheckConstraint("CK_Companies_StatusChangeReasonCode", "[StatusChangeReasonCode] IN (N'Created', N'Administrative', N'Operational', N'Compliance', N'CustomerRequest', N'IssueResolved')");
                        });
                });

            modelBuilder.Entity("SSAS.GL.Domain.Calendar.FiscalPeriod", b =>
                {
                    b.HasOne("SSAS.GL.Domain.Calendar.FiscalYear", null)
                        .WithMany("Periods")
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.GL.Domain.Calendar.FiscalYear", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.GL.Domain.Journals.JournalDraft", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.GL.Domain.Journals.JournalDraftLine", b =>
                {
                    b.HasOne("SSAS.GL.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.GL.Domain.Journals.JournalDraft", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalDraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.GL.Domain.Journals.JournalEntry", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.GL.Domain.Journals.JournalEntry", null)
                        .WithMany()
                        .HasForeignKey("ReversesJournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SSAS.GL.Domain.Journals.JournalLine", b =>
                {
                    b.HasOne("SSAS.GL.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.GL.Domain.Journals.JournalEntry", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.HR.Domain.Departments.Department", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.HR.Domain.Departments.Department", null)
                        .WithMany()
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SSAS.HR.Domain.Departments.DepartmentManager", b =>
                {
                    b.HasOne("SSAS.HR.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.HR.Domain.Departments.Department", null)
                        .WithOne()
                        .HasForeignKey("SSAS.HR.Domain.Departments.DepartmentManager", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.HR.Domain.Departments.EmployeeDepartmentAssignment", b =>
                {
                    b.HasOne("SSAS.HR.Domain.Departments.Department", null)
                        .WithMany()
                        .HasForeignKey("DestinationDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.HR.Domain.Employees.Employee", null)
                        .WithMany("DepartmentAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.HR.Domain.Departments.Department", null)
                        .WithMany()
                        .HasForeignKey("SourceDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SSAS.HR.Domain.Employees.Employee", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.Platform.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.HR.Domain.Departments.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.HR.Domain.Positions.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.HR.Domain.Employees.EmployeeBranchAssignment", b =>
                {
                    b.HasOne("SSAS.HR.Domain.Employees.Employee", null)
                        .WithMany("BranchAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.HR.Domain.ImportExport.EmployeeExportRun", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.HR.Domain.ImportExport.EmployeeImportRun", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.HR.Domain.Positions.EmployeePositionAssignment", b =>
                {
                    b.HasOne("SSAS.HR.Domain.Positions.Position", null)
                        .WithMany()
                        .HasForeignKey("DestinationPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.HR.Domain.Employees.Employee", null)
                        .WithMany("PositionAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.HR.Domain.Positions.Position", null)
                        .WithMany()
                        .HasForeignKey("SourcePositionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SSAS.HR.Domain.Positions.JobGrade", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.HR.Domain.Positions.SalaryGrade", null)
                        .WithMany()
                        .HasForeignKey("SalaryGradeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SSAS.HR.Domain.Positions.Position", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.HR.Domain.Positions.JobGrade", null)
                        .WithMany()
                        .HasForeignKey("JobGradeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SSAS.HR.Domain.Positions.SalaryGrade", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SSAS.HR.Domain.Positions.SalaryBand", "Band", b1 =>
                        {
                            b1.Property<Guid>("SalaryGradeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("MaximumAmount")
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("MaximumAmount");

                            b1.Property<decimal>("MidpointAmount")
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("MidpointAmount");

                            b1.Property<decimal>("MinimumAmount")
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("MinimumAmount");

                            b1.HasKey("SalaryGradeId");

                            b1.ToTable("SalaryGrades", "tenant");

                            b1.WithOwner()
                                .HasForeignKey("SalaryGradeId");
                        });

                    b.Navigation("Band");
                });

            modelBuilder.Entity("SSAS.Payroll.Domain.Compensation.EmployeeCompensation", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.Payroll.Domain.Compensation.PayElementAssignment", b =>
                {
                    b.HasOne("SSAS.Payroll.Domain.Compensation.EmployeeCompensation", null)
                        .WithMany("Assignments")
                        .HasForeignKey("EmployeeCompensationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.Payroll.Domain.Elements.PayElement", null)
                        .WithMany()
                        .HasForeignKey("PayElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.Payroll.Domain.Elements.PayElement", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.Payroll.Domain.Runs.PayrollPeriod", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.Payroll.Domain.Runs.PayrollRun", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.Payroll.Domain.Runs.PayrollPeriod", null)
                        .WithMany()
                        .HasForeignKey("PayrollPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.Payroll.Domain.Runs.PayrollRunDraftLine", b =>
                {
                    b.HasOne("SSAS.Payroll.Domain.Elements.PayElement", null)
                        .WithMany()
                        .HasForeignKey("PayElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.Payroll.Domain.Runs.PayrollRun", null)
                        .WithMany("DraftLines")
                        .HasForeignKey("PayrollRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.Payroll.Domain.Runs.PayrollRunLine", b =>
                {
                    b.HasOne("SSAS.Payroll.Domain.Elements.PayElement", null)
                        .WithMany()
                        .HasForeignKey("PayElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.Payroll.Domain.Runs.PayrollRun", null)
                        .WithMany("Lines")
                        .HasForeignKey("PayrollRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.GL.Domain.Calendar.FiscalYear", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("SSAS.GL.Domain.Journals.JournalDraft", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SSAS.GL.Domain.Journals.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SSAS.HR.Domain.Employees.Employee", b =>
                {
                    b.Navigation("BranchAssignments");

                    b.Navigation("DepartmentAssignments");

                    b.Navigation("PositionAssignments");
                });

            modelBuilder.Entity("SSAS.Payroll.Domain.Compensation.EmployeeCompensation", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("SSAS.Payroll.Domain.Runs.PayrollRun", b =>
                {
                    b.Navigation("DraftLines");

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
