using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1861

namespace SSAS.Platform.Infrastructure.Persistence.TenantErp.Migrations
{
    /// <summary>
    /// First migration of the TENANT stream (ADR-017 / ADR-018): creates the tenant ERP schema and moves
    /// Company into it from the platform schema.
    /// </summary>
    /// <remarks>
    /// The data move is written to be safe in EVERY deployment ordering, because the platform and tenant
    /// streams are independent and neither can force the other to run first:
    /// <list type="bullet">
    /// <item>It reads whichever source table exists — <c>platform.Companies</c> before the platform
    /// migration renames it, or <c>platform.Companies_MigratedToTenant</c> after. Either order preserves
    /// the data; no ordering loses it.</item>
    /// <item>It is idempotent. Rows already present in the target are skipped, so re-running the migration
    /// after a partial failure cannot duplicate or overwrite.</item>
    /// <item>It is a no-op on a fresh or dedicated database, where no platform schema exists at all.</item>
    /// </list>
    /// <c>RowVersion</c> is deliberately not copied: it is a SQL Server <c>rowversion</c>, generated by the
    /// target database and not insertable. Moved rows therefore receive new concurrency tokens, so a client
    /// holding a pre-move token gets a concurrency conflict rather than a silent overwrite — fail-loud, and
    /// the only available behaviour.
    /// </remarks>
    public partial class AddTenantCompanyOrganization : Migration
    {
        // Dynamic SQL is used so the guarded statement is never compiled when its source table is absent.
        private const string CopyColumns =
            "[CompanyId], [TenantId], [CompanyCode], [NormalizedCompanyCode], [CompanyName], " +
            "[BaseCurrencyCode], [Status], [StatusChangeReasonCode], [StatusChangedUtc], [StatusChangedBy], " +
            "[CreatedUtc], [ModifiedUtc], [CreatedBy], [ModifiedBy]";

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "tenant");

            migrationBuilder.CreateTable(
                name: "Companies",
                schema: "tenant",
                columns: table => new
                {
                    CompanyId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    TenantId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CompanyCode = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false),
                    NormalizedCompanyCode = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false, collation: "Latin1_General_100_BIN2"),
                    CompanyName = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    BaseCurrencyCode = table.Column<string>(type: "char(3)", fixedLength: true, maxLength: 3, nullable: false, collation: "Latin1_General_100_BIN2"),
                    Status = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: false, collation: "Latin1_General_100_BIN2"),
                    StatusChangeReasonCode = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: false, collation: "Latin1_General_100_BIN2"),
                    StatusChangedUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    StatusChangedBy = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false),
                    CreatedUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    ModifiedUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    ModifiedBy = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    RowVersion = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Companies", x => x.CompanyId);
                    table.CheckConstraint("CK_Companies_BaseCurrencyCode", "[BaseCurrencyCode] LIKE '[A-Z][A-Z][A-Z]'");
                    table.CheckConstraint("CK_Companies_CompanyCode_NotBlank", "LEN(LTRIM(RTRIM([CompanyCode]))) > 0");
                    table.CheckConstraint("CK_Companies_CompanyName_NotBlank", "LEN(LTRIM(RTRIM([CompanyName]))) > 0");
                    table.CheckConstraint("CK_Companies_Status", "[Status] IN (N'Inactive', N'Active', N'Archived')");
                    table.CheckConstraint("CK_Companies_StatusChangeReasonCode", "[StatusChangeReasonCode] IN (N'Created', N'Administrative', N'Operational', N'Compliance', N'CustomerRequest', N'IssueResolved')");
                });

            migrationBuilder.CreateIndex(
                name: "IX_Companies_TenantId_Status_CompanyName_CompanyId",
                schema: "tenant",
                table: "Companies",
                columns: new[] { "TenantId", "Status", "CompanyName", "CompanyId" });

            migrationBuilder.CreateIndex(
                name: "UX_Companies_TenantId_NormalizedCompanyCode",
                schema: "tenant",
                table: "Companies",
                columns: new[] { "TenantId", "NormalizedCompanyCode" },
                unique: true);

            // Database backstop for direct/batch SQL deletes, carried across with the table. TenantDbContext
            // rejects EF-tracked deletion; this covers everything that bypasses EF. Losing it in the move
            // would have quietly weakened Company's retention guarantee.
            migrationBuilder.Sql(
                """
                CREATE TRIGGER [tenant].[TR_Companies_PreventDelete]
                ON [tenant].[Companies]
                INSTEAD OF DELETE
                AS
                BEGIN
                  SET NOCOUNT ON;
                  THROW 51000, 'Company rows cannot be physically deleted; use the Archive lifecycle transition.', 1;
                END;
                """);

            // Move existing Company rows into tenant ownership. Today the shared tenant database is the
            // same SQL catalog as the Platform database, so this is a same-catalog copy; on a fresh or
            // dedicated database both guards are false and nothing happens.
            migrationBuilder.Sql(CopyFrom("[platform].[Companies]"));
            migrationBuilder.Sql(CopyFrom("[platform].[Companies_MigratedToTenant]"));
        }

        private static string CopyFrom(string sourceTable) =>
            $"""
            IF OBJECT_ID(N'{sourceTable}', N'U') IS NOT NULL
            BEGIN
                EXEC(N'
                    INSERT INTO [tenant].[Companies] ({CopyColumns})
                    SELECT {CopyColumns}
                    FROM {sourceTable} AS source
                    WHERE NOT EXISTS (
                        SELECT 1 FROM [tenant].[Companies] AS existing
                        WHERE existing.[CompanyId] = source.[CompanyId]);');
            END
            """;

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Companies",
                schema: "tenant");
        }
    }
}
