// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSAS.Platform.Infrastructure.Persistence.TenantErp;

#nullable disable

namespace SSAS.Platform.Infrastructure.Persistence.TenantErp.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260817181514_AddTenantBranch")]
    partial class AddTenantBranch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SSAS.Platform.Domain.Branches.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BranchId");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMainBranch")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedBranchCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("UX_Branches_TenantId_MainBranch")
                        .HasFilter("[IsMainBranch] = 1 AND [IsActive] = 1");

                    b.HasIndex("TenantId", "NormalizedBranchCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Branches_TenantId_NormalizedBranchCode");

                    b.HasIndex("TenantId", "IsActive", "BranchName")
                        .HasDatabaseName("IX_Branches_TenantId_IsActive_BranchName");

                    b.ToTable("Branches", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_Branches_BranchCode_NotBlank", "LEN(LTRIM(RTRIM([BranchCode]))) > 0");

                            t.HasCheckConstraint("CK_Branches_BranchName_NotBlank", "LEN(LTRIM(RTRIM([BranchName]))) > 0");
                        });
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<string>("BaseCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedCompanyCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StatusChangeReasonCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StatusChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("StatusChangedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedCompanyCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Companies_TenantId_NormalizedCompanyCode");

                    b.HasIndex("TenantId", "Status", "CompanyName", "Id")
                        .HasDatabaseName("IX_Companies_TenantId_Status_CompanyName_CompanyId");

                    b.ToTable("Companies", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_Companies_BaseCurrencyCode", "[BaseCurrencyCode] LIKE '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("CK_Companies_CompanyCode_NotBlank", "LEN(LTRIM(RTRIM([CompanyCode]))) > 0");

                            t.HasCheckConstraint("CK_Companies_CompanyName_NotBlank", "LEN(LTRIM(RTRIM([CompanyName]))) > 0");

                            t.HasCheckConstraint("CK_Companies_Status", "[Status] IN (N'Inactive', N'Active', N'Archived')");

                            t.HasCheckConstraint("CK_Companies_StatusChangeReasonCode", "[StatusChangeReasonCode] IN (N'Created', N'Administrative', N'Operational', N'Compliance', N'CustomerRequest', N'IssueResolved')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
