// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSAS.Platform.Infrastructure.Persistence.TenantErp;

#nullable disable

namespace SSAS.Platform.Infrastructure.Persistence.TenantErp.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    partial class TenantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SSAS.HR.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeId");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("EmploymentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NormalizedEmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("NormalizedNationalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StatusChangeReasonCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StatusChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("StatusChangedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("TerminationDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TenantId", "CompanyId", "NormalizedEmployeeNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Employees_TenantId_CompanyId_NormalizedEmployeeNumber");

                    b.HasIndex("TenantId", "CompanyId", "NormalizedNationalId")
                        .IsUnique()
                        .HasDatabaseName("UX_Employees_TenantId_CompanyId_NormalizedNationalId")
                        .HasFilter("[NormalizedNationalId] IS NOT NULL");

                    b.HasIndex("TenantId", "CompanyId", "BranchId", "Status")
                        .HasDatabaseName("IX_Employees_TenantId_CompanyId_BranchId_Status");

                    b.ToTable("Employees", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_Employees_EmployeeNumber_NotBlank", "LEN(LTRIM(RTRIM([EmployeeNumber]))) > 0");

                            t.HasCheckConstraint("CK_Employees_FullName_NotBlank", "LEN(LTRIM(RTRIM([FullName]))) > 0");

                            t.HasCheckConstraint("CK_Employees_Status", "[Status] IN (N'Active', N'Inactive', N'Terminated')");

                            t.HasCheckConstraint("CK_Employees_StatusChangeReasonCode", "[StatusChangeReasonCode] IN (N'Created', N'Administrative', N'Operational', N'Compliance', N'Resignation', N'Dismissal', N'EndOfContract')");

                            t.HasCheckConstraint("CK_Employees_TerminationDateMatchesStatus", "([Status] = N'Terminated' AND [TerminationDate] IS NOT NULL) OR ([Status] <> N'Terminated' AND [TerminationDate] IS NULL)");

                            t.HasCheckConstraint("CK_Employees_TerminationNotBeforeEmployment", "[TerminationDate] IS NULL OR [TerminationDate] >= [EmploymentDate]");
                        });
                });

            modelBuilder.Entity("SSAS.HR.Domain.Employees.EmployeeBranchAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeBranchAssignmentId");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DestinationBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ReasonText")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("SourceBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransferredBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TenantId", "CompanyId", "DestinationBranchId", "EffectiveFromUtc")
                        .HasDatabaseName("IX_EmployeeBranchAssignments_TenantId_CompanyId_DestinationBranchId_EffectiveFromUtc");

                    b.HasIndex("TenantId", "EmployeeId", "EffectiveFromUtc", "Id")
                        .HasDatabaseName("IX_EmployeeBranchAssignments_TenantId_EmployeeId_EffectiveFromUtc_Id");

                    b.ToTable("EmployeeBranchAssignments", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeBranchAssignments_InitialAssignmentHasNoSource", "([SourceBranchId] IS NULL AND [ReasonCode] = N'InitialAssignment') OR ([SourceBranchId] IS NOT NULL AND [ReasonCode] <> N'InitialAssignment')");

                            t.HasCheckConstraint("CK_EmployeeBranchAssignments_ReasonCode", "[ReasonCode] IN (N'InitialAssignment', N'Reorganisation', N'OperationalNeed', N'EmployeeRequest', N'BranchClosure', N'Correction')");

                            t.HasCheckConstraint("CK_EmployeeBranchAssignments_SourceDiffersFromDestination", "[SourceBranchId] IS NULL OR [SourceBranchId] <> [DestinationBranchId]");
                        });
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Branches.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BranchId");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMainBranch")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedBranchCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("UX_Branches_TenantId_MainBranch")
                        .HasFilter("[IsMainBranch] = 1 AND [IsActive] = 1");

                    b.HasIndex("TenantId", "NormalizedBranchCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Branches_TenantId_NormalizedBranchCode");

                    b.HasIndex("TenantId", "IsActive", "BranchName")
                        .HasDatabaseName("IX_Branches_TenantId_IsActive_BranchName");

                    b.ToTable("Branches", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_Branches_BranchCode_NotBlank", "LEN(LTRIM(RTRIM([BranchCode]))) > 0");

                            t.HasCheckConstraint("CK_Branches_BranchName_NotBlank", "LEN(LTRIM(RTRIM([BranchName]))) > 0");
                        });
                });

            modelBuilder.Entity("SSAS.Platform.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<string>("BaseCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedCompanyCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StatusChangeReasonCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("StatusChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("StatusChangedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedCompanyCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Companies_TenantId_NormalizedCompanyCode");

                    b.HasIndex("TenantId", "Status", "CompanyName", "Id")
                        .HasDatabaseName("IX_Companies_TenantId_Status_CompanyName_CompanyId");

                    b.ToTable("Companies", "tenant", t =>
                        {
                            t.HasCheckConstraint("CK_Companies_BaseCurrencyCode", "[BaseCurrencyCode] LIKE '[A-Z][A-Z][A-Z]'");

                            t.HasCheckConstraint("CK_Companies_CompanyCode_NotBlank", "LEN(LTRIM(RTRIM([CompanyCode]))) > 0");

                            t.HasCheckConstraint("CK_Companies_CompanyName_NotBlank", "LEN(LTRIM(RTRIM([CompanyName]))) > 0");

                            t.HasCheckConstraint("CK_Companies_Status", "[Status] IN (N'Inactive', N'Active', N'Archived')");

                            t.HasCheckConstraint("CK_Companies_StatusChangeReasonCode", "[StatusChangeReasonCode] IN (N'Created', N'Administrative', N'Operational', N'Compliance', N'CustomerRequest', N'IssueResolved')");
                        });
                });

            modelBuilder.Entity("SSAS.HR.Domain.Employees.Employee", b =>
                {
                    b.HasOne("SSAS.Platform.Domain.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SSAS.Platform.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.HR.Domain.Employees.EmployeeBranchAssignment", b =>
                {
                    b.HasOne("SSAS.HR.Domain.Employees.Employee", null)
                        .WithMany("BranchAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SSAS.HR.Domain.Employees.Employee", b =>
                {
                    b.Navigation("BranchAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
